<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by PlexiLisp 2.0.4 on Tue Jul 31 16:01:25 2007 -->
<PlexilPlan>
  <Node NodeType="Empty">
    <NodeId>Root</NodeId>
    <VariableDeclarations>
      <DeclareVariable>
        <Name>foo</Name>
        <Type>String</Type>
        <InitialValue>
          <StringValue>""</StringValue>
        </InitialValue>
      </DeclareVariable>
    </VariableDeclarations>
  </Node>
</PlexilPlan>
