<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Thu Jan 24 14:17:37 2008 -->
<PlexilPlan>
  <Node NodeType="LibraryNodeCall" >
    <NodeId>root</NodeId>
    <VariableDeclarations>
      <DeclareVariable>
        <Name>name</Name>
        <Type>String</Type>
      </DeclareVariable>
    </VariableDeclarations>
    <EndCondition>
      <IsKnown>
        <StringVariable>name</StringVariable>
      </IsKnown>
    </EndCondition>
    <NodeBody>
      <LibraryNodeCall>
        <NodeId>library6</NodeId>
        <Alias>
          <NodeParameter>x</NodeParameter>
          <StringVariable>name</StringVariable>
        </Alias>
        <Alias>
          <NodeParameter>y</NodeParameter>
          <StringValue>foo</StringValue>
        </Alias>
      </LibraryNodeCall>
    </NodeBody>
  </Node>
</PlexilPlan>
