<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Thu Jan 24 13:42:25 2008 -->
<PlexilPlan>
  <Node NodeType="Assignment" >
    <NodeId>library6</NodeId>
    <Interface>
      <InOut>
        <DeclareVariable>
          <Name>x</Name>
          <Type>String</Type>
        </DeclareVariable>
      </InOut>
      <In>
        <DeclareVariable>
          <Name>y</Name>
          <Type>String</Type>
        </DeclareVariable>
      </In>
    </Interface>
    <NodeBody>
      <Assignment>
        <StringVariable>x</StringVariable>
        <StringRHS>
          <LookupNow>
            <Name>
              <StringValue>foo</StringValue>
            </Name>
            <Arguments>
              <StringVariable>y</StringVariable>
            </Arguments>
          </LookupNow>
        </StringRHS>
      </Assignment>
    </NodeBody>
  </Node>
</PlexilPlan>
