<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan><Node NodeType="Update"><NodeId>array8</NodeId><VariableDeclarations>
      <DeclareArray>
        <Name>src</Name>
        <Type>Real</Type>
        <MaxSize>2</MaxSize>
        <InitialValue>
          <RealValue>5.0</RealValue>
          <RealValue>6.0</RealValue>
        </InitialValue>
      </DeclareArray>
    </VariableDeclarations><NodeBody>
      <Update>
        <Pair>
          <Name>val</Name>
          <ArrayVariable>src</ArrayVariable>
        </Pair>
      </Update>
    </NodeBody></Node></PlexilPlan>