<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan><Node NodeType="Empty"><NodeId>boolean1</NodeId><PreCondition><LookupNow>
        <Name>
<StringValue>flag</StringValue>
        </Name>
      </LookupNow></PreCondition></Node></PlexilPlan>