<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan><Node NodeType="NodeList"><NodeId>command3</NodeId><VariableDeclarations>
      <DeclareVariable>
        <Name>result-string</Name>
        <Type>String</Type>
      </DeclareVariable>
    </VariableDeclarations><NodeBody>
      <NodeList>
        <Node NodeType="Command"><NodeId>StringCommand</NodeId><NodeBody>
            <Command>
              <StringVariable>result-string</StringVariable>
              <Name>
<StringValue>get-string</StringValue>
              </Name>
            </Command>
          </NodeBody></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>