<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan><Node NodeType="Command"><NodeId>command1</NodeId><VariableDeclarations>
      <DeclareVariable>
        <Name>CommandName</Name>
        <Type>String</Type>
        <InitialValue>
<StringValue>foo</StringValue>
        </InitialValue>
      </DeclareVariable>
    </VariableDeclarations><NodeBody>
      <Command>
        <Name>
          <StringVariable>CommandName</StringVariable>
        </Name>
        <Arguments>
<StringValue/>
        </Arguments>
      </Command>
    </NodeBody></Node></PlexilPlan>