<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan><Node NodeType="NodeList"><NodeId>empty3</NodeId><EndCondition><EQInternal><NodeStateVariable><NodeId>two</NodeId></NodeStateVariable><NodeStateValue>FINISHED</NodeStateValue></EQInternal></EndCondition><PostCondition><AND><EQInternal><NodeStateVariable><NodeId>two</NodeId></NodeStateVariable><NodeStateValue>FINISHED</NodeStateValue></EQInternal><EQInternal><NodeOutcomeVariable><NodeId>two</NodeId></NodeOutcomeVariable><NodeOutcomeValue>SUCCESS</NodeOutcomeValue></EQInternal></AND></PostCondition><NodeBody>
      <NodeList>
        <Node NodeType="Empty"><NodeId>one</NodeId></Node>
        <Node NodeType="Empty"><NodeId>two</NodeId><StartCondition><EQInternal><NodeStateVariable><NodeId>one</NodeId></NodeStateVariable><NodeStateValue>FINISHED</NodeStateValue></EQInternal></StartCondition></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>