<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan><Node NodeType="Empty"><NodeId>EmptyString1</NodeId><VariableDeclarations>
      <DeclareVariable>
        <Name>foo</Name>
        <Type>String</Type>
        <InitialValue>
<StringValue/>
        </InitialValue>
      </DeclareVariable>
    </VariableDeclarations></Node></PlexilPlan>