<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Wed Feb 20 14:23:12 2008 -->
<PlexilPlan>
  <Node NodeType="NodeList" >
    <NodeId>Root</NodeId>
    <VariableDeclarations>
      <DeclareVariable>
        <Name>foo</Name>
        <Type>Integer</Type>
      </DeclareVariable>
      <DeclareVariable>
        <Name>bar</Name>
        <Type>Integer</Type>
		<InitialValue>
		  <IntegerValue>42</IntegerValue>
		</InitialValue>
      </DeclareVariable>
    </VariableDeclarations>
	<PostCondition>
	  <AND>
		<EQNumeric>
		  <IntegerVariable>foo</IntegerVariable>
		  <IntegerValue>42</IntegerValue>
		</EQNumeric>
		<EQNumeric>
		  <IntegerVariable>bar</IntegerVariable>
		  <IntegerValue>55</IntegerValue>
		</EQNumeric>
	  </AND>
	</PostCondition>
    <NodeBody>
      <NodeList>
        <Node NodeType="Assignment" >
          <NodeId>One</NodeId>
          <NodeBody>
            <Assignment>
              <IntegerVariable>bar</IntegerVariable>
              <NumericRHS>
                <IntegerValue>55</IntegerValue>
              </NumericRHS>
            </Assignment>
          </NodeBody>
        </Node>
        <Node NodeType="Assignment" >
          <NodeId>Two</NodeId>
<!-- The following interface declaration, in combination with bar's assignment above, breaks this plan. -->
          <Interface>
            <In>
              <DeclareVariable>
                <Name>bar</Name>
                <Type>Integer</Type>
              </DeclareVariable>
            </In>
          </Interface>
          <NodeBody>
            <Assignment>
              <IntegerVariable>foo</IntegerVariable>
              <NumericRHS>
                <IntegerVariable>bar</IntegerVariable>
              </NumericRHS>
            </Assignment>
          </NodeBody>
        </Node>
      </NodeList>
    </NodeBody>
  </Node>
</PlexilPlan>
