<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan><Node NodeType="Assignment"><NodeId>library6</NodeId><Interface><In><DeclareVariable>
          <Name>y</Name>
          <Type>String</Type>
        </DeclareVariable></In><InOut><DeclareVariable>
          <Name>x</Name>
          <Type>String</Type>
        </DeclareVariable></InOut></Interface><NodeBody>
      <Assignment>
        <StringVariable>x</StringVariable>
        <StringRHS>
          <StringVariable>y</StringVariable>
        </StringRHS>
      </Assignment>
    </NodeBody></Node></PlexilPlan>