<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan><Node NodeType="LibraryNodeCall"><NodeId>LibraryCall6</NodeId><VariableDeclarations>
      <DeclareVariable>
        <Name>name</Name>
        <Type>String</Type>
      </DeclareVariable>
    </VariableDeclarations><EndCondition><IsKnown><StringVariable>name</StringVariable></IsKnown></EndCondition><PostCondition><AND><EQInternal><NodeStateVariable><NodeId>library6</NodeId></NodeStateVariable><NodeStateValue>FINISHED</NodeStateValue></EQInternal><EQInternal><NodeOutcomeVariable><NodeId>library6</NodeId></NodeOutcomeVariable><NodeOutcomeValue>SUCCESS</NodeOutcomeValue></EQInternal></AND></PostCondition><NodeBody>
      <LibraryNodeCall>
        <NodeId>library6</NodeId>
        <Alias>
          <NodeParameter>x</NodeParameter>
          <StringVariable>name</StringVariable>
        </Alias>
        <Alias>
          <NodeParameter>y</NodeParameter>
<StringValue>foo</StringValue>
        </Alias>
      </LibraryNodeCall>
    </NodeBody></Node></PlexilPlan>