<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:tr="extended-plexil-translator">
   <Node NodeType="LibraryNodeCall">
      <NodeId>root</NodeId>
      <VariableDeclarations>
         <DeclareVariable>
            <Name>name</Name>
            <Type>String</Type>
         </DeclareVariable>
      </VariableDeclarations>
      <EndCondition>
         <IsKnown>
            <StringVariable>name</StringVariable>
         </IsKnown>
      </EndCondition>
      <NodeBody>
         <LibraryNodeCall>
            <NodeId>library6</NodeId>
            <Alias>
               <NodeParameter>x</NodeParameter>
               <StringVariable>name</StringVariable>
            </Alias>
            <Alias>
               <NodeParameter>y</NodeParameter>
               <StringValue>foo</StringValue>
            </Alias>
         </LibraryNodeCall>
      </NodeBody>
   </Node>
</PlexilPlan>