<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan><Node NodeType="Assignment"><NodeId>lookup3</NodeId><VariableDeclarations>
      <DeclareVariable>
        <Name>x</Name>
        <Type>Integer</Type>
      </DeclareVariable>
    </VariableDeclarations><NodeBody>
      <Assignment>
        <IntegerVariable>x</IntegerVariable>
        <NumericRHS>
          <LookupNow>
            <Name>
<StringValue>foo</StringValue>
            </Name>
          </LookupNow>
        </NumericRHS>
      </Assignment>
    </NodeBody></Node></PlexilPlan>