<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan><Node NodeType="NodeList"><NodeId>repeat5</NodeId><RepeatCondition><LookupOnChange>
        <Name>
<StringValue>continue</StringValue>
        </Name>
      </LookupOnChange></RepeatCondition><NodeBody>
      <NodeList>
        <Node NodeType="Command"><NodeId>Command</NodeId><NodeBody>
            <Command>
              <Name>
<StringValue>foo</StringValue>
              </Name>
            </Command>
          </NodeBody></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>