<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan><Node NodeType="Command"><NodeId>repeat7</NodeId><RepeatCondition><LookupOnChange>
        <Name>
<StringValue>continue</StringValue>
        </Name>
      </LookupOnChange></RepeatCondition><NodeBody>
      <Command>
        <Name>
<StringValue>foo</StringValue>
        </Name>
      </Command>
    </NodeBody></Node></PlexilPlan>