<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by PlexiLisp -->
<PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <Node NodeType="Command">
      <NodeId>Root</NodeId>
      <Priority>2</Priority>
      <VariableDeclarations>
         <DeclareVariable>
            <Name>p</Name>
            <Type>Real</Type>
         </DeclareVariable>
      </VariableDeclarations>
      <NodeBody>
         <Command>
            <ResourceList>
               <Resource>
                  <ResourceName>
                     <StringValue>Memory</StringValue>
                  </ResourceName>
                  <ResourceUpperBound>
                     <RealValue>20.0</RealValue>
                  </ResourceUpperBound>
               </Resource>
            </ResourceList>
            <RealVariable>p</RealVariable>
            <Name>
               <StringValue>store</StringValue>
            </Name>
         </Command>
      </NodeBody>
   </Node>
</PlexilPlan>
