<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan><Node NodeType="NodeList"><NodeId>Root</NodeId><PostCondition><EQInternal><NodeOutcomeVariable><NodeId>SkipMe</NodeId></NodeOutcomeVariable><NodeOutcomeValue>SKIPPED</NodeOutcomeValue></EQInternal></PostCondition><NodeBody>
      <NodeList>
        <Node NodeType="Empty"><NodeId>SkipMe</NodeId><SkipCondition><BooleanValue>1</BooleanValue></SkipCondition></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>