<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Thu May  1 16:56:01 2008 -->
<PlexilPlan>
<!-- Tests arrays as update values -->
  <Node NodeType="Update" >
    <NodeId>Root</NodeId>
    <VariableDeclarations>
      <DeclareArray>
        <Name>src</Name>
        <Type>Real</Type>
        <MaxSize>2</MaxSize>
        <InitialValue>
          <RealValue>5.0</RealValue>
          <RealValue>6.0</RealValue>
        </InitialValue>
      </DeclareArray>
    </VariableDeclarations>
    <NodeBody>
      <Update>
        <Pair>
          <Name>val</Name>
          <ArrayVariable>src</ArrayVariable>
        </Pair>
      </Update>
    </NodeBody>
  </Node>
</PlexilPlan>
