<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by PlexiLisp 2.0.4 on Tue Aug  7 14:43:56 2007 -->
<PlexilPlan>
  <Node NodeType="NodeList">
    <NodeId>root</NodeId>
    <EndCondition>
      <EQInternal>
        <NodeStateVariable>
          <NodeId>two</NodeId>
        </NodeStateVariable>
        <NodeStateValue>FINISHED</NodeStateValue>
      </EQInternal>
    </EndCondition>
    <PostCondition>
      <EQInternal>
        <NodeOutcomeVariable>
          <NodeId>two</NodeId>
        </NodeOutcomeVariable>
        <NodeOutcomeValue>SUCCESS</NodeOutcomeValue>
      </EQInternal>
    </PostCondition>
    <NodeBody>
      <NodeList>
        <Node NodeType="Empty">
          <NodeId>one</NodeId>
        </Node>
        <Node NodeType="Empty">
          <NodeId>two</NodeId>
          <StartCondition>
            <EQInternal>
              <NodeStateVariable>
                <NodeId>one</NodeId>
              </NodeStateVariable>
              <NodeStateValue>FINISHED</NodeStateValue>
            </EQInternal>
          </StartCondition>
        </Node>
      </NodeList>
    </NodeBody>
  </Node>
</PlexilPlan>
