  <PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://plexil.svn.sourceforge.net/viewvc/plexil/trunk/schema/core-plexil.xsd" FileName="lib2.ple">
      <GlobalDeclarations/>
      <Node FileName="lib2.ple" LineNo="5" ColNo="1" NodeType="NodeList">
          <Interface>
              <In>
                  <DeclareVariable>
                      <Name>y</Name>
                      <Type>Real</Type>
                  </DeclareVariable>
                  <DeclareVariable>
                      <Name>z</Name>
                      <Type>Real</Type>
                  </DeclareVariable>
              </In>
          </Interface>
          <NodeId>LibTest2</NodeId>
          <NodeBody>
              <NodeList>
                  <Node FileName="lib2.ple" LineNo="14" ColNo="13" NodeType="Command">
                      <NodeId>BarCall2</NodeId>
                      <NodeBody>
                          <Command>
                              <Name>
                                  <StringValue>bar</StringValue>
                              </Name>
                              <Arguments>
                                  <RealVariable>y</RealVariable>
                                  <RealVariable>z</RealVariable>
                              </Arguments>
                          </Command>
                      </NodeBody>
                  </Node>
                  <Node FileName="lib2.ple" LineNo="19" ColNo="4" NodeType="LibraryNodeCall">
                      <NodeId>Call2LibTest1</NodeId>
                      <NodeBody>
                          <LibraryNodeCall>
                              <NodeId>LibTest1</NodeId>
                              <Alias>
                                  <NodeParameter>lb</NodeParameter>
                                  <BooleanValue>false</BooleanValue>
                              </Alias>
                              <Alias>
                                  <NodeParameter>li</NodeParameter>
                                  <IntegerValue>123</IntegerValue>
                              </Alias>
                              <Alias>
                                  <NodeParameter>lr</NodeParameter>
                                  <RealVariable>y</RealVariable>
                              </Alias>
                              <Alias>
                                  <NodeParameter>ls</NodeParameter>
                                  <StringValue>what!</StringValue>
                              </Alias>
                          </LibraryNodeCall>
                      </NodeBody>
                  </Node>
              </NodeList>
          </NodeBody>
      </Node>
  </PlexilPlan>
