  <PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://plexil.svn.sourceforge.net/viewvc/plexil/trunk/schema/core-plexil.xsd" FileName="libcall.ple">
      <GlobalDeclarations/>
      <Node FileName="libcall.ple" LineNo="5" ColNo="1" NodeType="NodeList">
          <NodeId>List</NodeId>
          <VariableDeclarations>
              <DeclareVariable>
                  <Name>b</Name>
                  <Type>Boolean</Type>
                  <InitialValue>
                      <BooleanValue>true</BooleanValue>
                  </InitialValue>
              </DeclareVariable>
              <DeclareVariable>
                  <Name>i</Name>
                  <Type>Integer</Type>
                  <InitialValue>
                      <IntegerValue>1966</IntegerValue>
                  </InitialValue>
              </DeclareVariable>
              <DeclareVariable>
                  <Name>r</Name>
                  <Type>Real</Type>
                  <InitialValue>
                      <RealValue>3.1415</RealValue>
                  </InitialValue>
              </DeclareVariable>
              <DeclareVariable>
                  <Name>s</Name>
                  <Type>String</Type>
                  <InitialValue>
                      <StringValue>hello</StringValue>
                  </InitialValue>
              </DeclareVariable>
          </VariableDeclarations>
          <NodeBody>
              <NodeList>
                  <Node FileName="libcall.ple" LineNo="19" ColNo="4" NodeType="LibraryNodeCall">
                      <NodeId>CallLibTest1</NodeId>
                      <StartCondition>
                          <EQInternal>
                              <NodeOutcomeVariable>
                                  <NodeId>CallLibTest2</NodeId>
                              </NodeOutcomeVariable>
                              <NodeOutcomeValue>SUCCESS</NodeOutcomeValue>
                          </EQInternal>
                      </StartCondition>
                      <NodeBody>
                          <LibraryNodeCall>
                              <NodeId>LibTest1</NodeId>
                              <Alias>
                                  <NodeParameter>lb</NodeParameter>
                                  <BooleanVariable>b</BooleanVariable>
                              </Alias>
                              <Alias>
                                  <NodeParameter>li</NodeParameter>
                                  <IntegerVariable>i</IntegerVariable>
                              </Alias>
                              <Alias>
                                  <NodeParameter>lr</NodeParameter>
                                  <RealVariable>r</RealVariable>
                              </Alias>
                              <Alias>
                                  <NodeParameter>ls</NodeParameter>
                                  <StringVariable>s</StringVariable>
                              </Alias>
                          </LibraryNodeCall>
                      </NodeBody>
                  </Node>
                  <Node FileName="libcall.ple" LineNo="28" ColNo="4" NodeType="LibraryNodeCall">
                      <NodeId>CallLibTest2</NodeId>
                      <NodeBody>
                          <LibraryNodeCall>
                              <NodeId>LibTest2</NodeId>
                              <Alias>
                                  <NodeParameter>y</NodeParameter>
                                  <RealVariable>r</RealVariable>
                              </Alias>
                              <Alias>
                                  <NodeParameter>z</NodeParameter>
                                  <RealVariable>r</RealVariable>
                              </Alias>
                          </LibraryNodeCall>
                      </NodeBody>
                  </Node>
              </NodeList>
          </NodeBody>
      </Node>
  </PlexilPlan>
