<?xml version="1.0" encoding="UTF-8"?>
<PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="http://plexil.svn.sourceforge.net/viewvc/plexil/trunk/schema/core-plexil.xsd">
  <Node NodeType="FunctionCall">
    <NodeId>SimpleFunction</NodeId>
      <VariableDeclarations>
      <DeclareVariable>
        <Name>retTestFunction</Name>
        <Type>Integer</Type>
        <InitialValue>
          <IntegerValue>0</IntegerValue>
        </InitialValue>
      </DeclareVariable>
      <DeclareVariable>
        <Name>arg1</Name>
        <Type>Real</Type>
        <InitialValue>
          <RealValue>1.1</RealValue>
        </InitialValue>
      </DeclareVariable>
      <DeclareVariable>
        <Name>arg2</Name>
        <Type>Real</Type>
        <InitialValue>
          <RealValue>2.1</RealValue>
        </InitialValue>
      </DeclareVariable>
      </VariableDeclarations>
    <NodeBody>
      <FunctionCall>
        <IntegerVariable>retTestFunction</IntegerVariable>
        <FunctionName>testFunction</FunctionName>
          <Arguments>
            <RealVariable>arg1</RealVariable>
            <RealVariable>arg2</RealVariable>
          </Arguments>
      </FunctionCall>
    </NodeBody>
  </Node>
</PlexilPlan>
