<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.4 on Tue Aug 14 13:08:08 2007 -->
<PLEXILScript>
 <InitialState></InitialState>
 <Script>
  <FunctionCall name="add" type="real" >
   <Param type="real" >2.5</Param>
   <Param type="real" >2.0</Param>
   <Result>4.5</Result>
  </FunctionCall>
 </Script>
</PLEXILScript>
