#! /bin/sh

# Copyright (c) 2006-2009, Universities Space Research Association (USRA).
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Universities Space Research Association nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

usage="Usage: run-ue-ipc [-s] [-v [-h <hostname>] [-n <portnumber>] -b] [-d <debug file>] \
                         [-eprompt] [-wprompt] [-log <log file>] \
                         <plan> [-l <library>]*"

# Convenient though stylized script for running exec-test-runner_g_rt.
# Requires environment variable UE_HOME to be set to desired Exec/test directory.
# An optional environment variable UE_EXECUTABLE names an alternate executable.
# Other options:
#
#  -s suppresses a leading printed summary.
#  -v requests that plan state be transmitted to the UE viewer.
#  -h hostname of viewer
#  -n portnumber of viewer
#  -d debug file (default is Debug.cfg)


. $PLEXIL_HOME/bin/plexil-setup.sh

if [ -f $PLEXIL_HOME/bin/MultiExec ]
then
    prog=$PLEXIL_HOME/bin/MultiExec
elif [ -f $PLEXIL_HOME/src/apps/MultiExec/MultiExec ]
then
    prog=$PLEXIL_HOME/src/apps/MultiExec/MultiExec
else
    echo "UE executable not found, aborting"
    exit 1
fi

$PLEXIL_HOME/bin/plexil-check-prog $prog

# Check for summary suppression
if [ '-s' = "$1" ]
  then
    summary=0
    shift
  else
    summary=1
fi

# Check for viewer request
if [ '-v' = "$1" ]
  then
    viewer=-v
    shift
  else
    viewer=
fi

# Check for viewer host name
if [ '-h' = "$1" ]
  then
    host="-h $2"
    shift
    shift
  else
    host=
fi

# Check for viewer port number
if [ '-n' = "$1" ]
  then
    port="-n $2"
    shift
    shift
  else
    port=
fi

# Check for viewer should block
if [ '-b' = "$1" ]
  then
    block="-b"
    shift
  else
    block=
fi

# Check for specified debug file
if [ '-d' = "$1" ]
  then
    shift
    debug_file="$1"
    shift
  else
    debug_file="Debug.cfg"
fi

# Check for error prompt requested
if [ '-eprompt' = "$1" ]
  then
    eprompt="$1"
    shift
  else
    eprompt=
fi

# Check for warning prompt requested
if [ '-wprompt' = "$1" ]
  then
    wprompt="$1"
    shift
  else
    wprompt=
fi

# Check for specified log file
if [ '-log' = "$1" ]
  then 
    shift
    log_file="-log $1"
    shift
  else
    log_file=
fi

# Any more arguments?
if [ $# -eq 0 ]
  then
    echo $usage
    exit 1
fi

# Process first argument, which is the plan.
plan=$1
shift

# Check the plan's existence
if [ ! -e $plan ]
  then
    echo Error: Plan $plan does not exist.
    exit 1
fi

# The only valid next argument left is "-l", which precedes each library
if [ $# -gt 0 ]
  then
    if [ '-l' = $1 ] 
      then
        libraries=$*
      else
        echo Error: expected -l at this point
        echo $usage
        exit 1
    fi
fi

$prog -p $plan -d $debug_file $* $eprompt $wprompt $log_file $viewer $host $port $block
