#! /bin/sh
# Meant to be sourced, not executed

compiler_validation_tests='AddArray AnyArgs_empty_test ArglistArithmeticType ArrayEquality
ArrayLookup array-add array-complex array-copy array_size_test
assignment0 assignment1 assignment2
basic-wait-test boolean1 boolean2 boolean3 boolean4 boolean5
CallWithPostCondition CallNodeWithPostCondition
command0 command1 command2 command3 command4 command5 command-handle1
comment1 ComputedCommandName concat1 concurrence0 concurrence1 concurrence2
concurrence3 CopyReals CruiseControl
date1 Decrement Do1 Do2 Do3
DriveToSchool DriveToTarget duplicate-node-name
empty0 empty1 empty2 empty3 empty4 empty5 empty6 empty7 empty8
Exchange executing1 executing2 expr1 expr3 expr4
failed1 Fibs FibsNode Fib PrintFib PrintFibNode FibTest FibNodeTest finished1 for1 for2
if2 if3 if4 ifWithClauseIds inactive1 Increment interface-test interface-test1
invariantFail1 isKnown1
iterationEnded1 iterationFailed1 iterationSucceeded1
LibraryCall1 LibraryCall2 LibraryCall3 LibraryCall4 library-call1
LibraryCallWithArray library-node1 literal-format-test
lookup2 LookupWithComputedStateName
maxTest minTest mod1
NestedBlocks1 NestedBlocks2 NestedBlocks3 NestedBlocks4 NestedBlocks5
NestedBlocks6 NestedBlocks7 NoChildFailedTest nodeOutcome1 nodeState1 nodeState2
on-command1 on-command2 on-message1 on-message2
preconditionFailed1
resource0 Resource1 Resource2 Resource3 Resource4
RoboSimSimple2 SafeDrive
sequence0 sequence1 sequence2 sequence3
checked-sequence0 checked-sequence1 checked-sequence2 checked-sequence3
unchecked-sequence0 unchecked-sequence1 unchecked-sequence2 unchecked-sequence3
simpleIf SimpleDrive simpleIfThenElse simpleAssignment skipped1
StringConcat1 StringConcat2 StringConcat3 StringConcat4 StringConcat5
StringConcat6 StringConcat7 StringConcat8 strlen_test
succeeded1 Sum sync-cmd-test sync-cmd-test1 sync-cmd-options-test
test-recv test-send time-lookup-test time-lookup-test1 time_tolerance_test
timed-iteration tolerance1 try1
UnaryMinus update1 update2 update3
wait1 waiting1 While0 while1'

syntax_error_tests='array-library-call array-library-node-call'

semantic_error_tests='BadArrayAdd BadArrayLookup badNodeNameTest BadResource0
duplicateLookupDecl1 expr5 expr2
lookup1 LibraryCall5 LibraryCall6
on-message3 SeekGoalAndEnergy SeekGoalAndEnergyNode'
