<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Fri Aug 24 14:22:06 2007 -->
<PLEXILScript>
  <InitialState>
<!--     <State name="s2" type="string"> -->
<!--       <Value>foobar</Value> -->
<!--     </State> -->
    <State name="a5" type="real-array" >
      <Value>1.1</Value>
      <Value>2.2</Value>
      <Value>3.3</Value>
      <Value>4.4</Value>
    </State>
  </InitialState>
  <Script></Script>
</PLEXILScript>
