<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by PlexiLisp 2.0.3 on Tue Jun  5 12:44:45 2007 -->
<PLEXILScript>
  <InitialState>
    <State name="foo" type="int">
      <Value>5</Value>
    </State>
  </InitialState>
  <Script></Script>
</PLEXILScript>
