<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by PlexiLisp 2.0.4 on Fri Jul 27 13:50:35 2007 -->
<PlexilPlan>
  <Node NodeType="Empty">
    <NodeId>Root</NodeId>
    <PostCondition>
      <EQNumeric>
        <IntegerValue>1</IntegerValue>
        <IntegerValue>2</IntegerValue>
      </EQNumeric>
    </PostCondition>
    <SkipCondition>
      <BooleanValue>1</BooleanValue>
    </SkipCondition>
  </Node>
</PlexilPlan>
