<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="NodeList"><NodeId>plexilisp_Name_1</NodeId><VariableDeclarations>
      <DeclareVariable>
        <Name>foo</Name>
        <Type>Integer</Type>
      </DeclareVariable>
    </VariableDeclarations><NodeBody>
      <Assignment>
        <IntegerVariable>foo</IntegerVariable>
        <NumericRHS>
          <IntegerValue>4</IntegerValue>
        </NumericRHS>
      </Assignment>
    </NodeBody></Node></PlexilPlan>