<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="NodeList"><NodeId>FailureType1</NodeId><NodeBody>
      <NodeList>
        <Node NodeType="Empty"><NodeId>One</NodeId><PostCondition><EQNumeric><IntegerValue>1</IntegerValue><IntegerValue>0</IntegerValue></EQNumeric></PostCondition></Node>
        <Node NodeType="Empty"><NodeId>Two</NodeId><EndCondition><PostconditionFailed>
              <NodeId>One</NodeId>
            </PostconditionFailed></EndCondition></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>