<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="NodeList"><NodeId>Root</NodeId><Interface><In><DeclareVariable>
          <Name>bar</Name>
          <Type>Integer</Type>
          <InitialValue>
            <IntegerValue>5</IntegerValue>
          </InitialValue>
        </DeclareVariable></In></Interface><VariableDeclarations>
      <DeclareVariable>
        <Name>foo</Name>
        <Type>Integer</Type>
        <InitialValue>
          <IntegerValue>0</IntegerValue>
        </InitialValue>
      </DeclareVariable>
    </VariableDeclarations><PostCondition><AND><Succeeded>
          <NodeId>one</NodeId>
        </Succeeded><Succeeded>
          <NodeId>two</NodeId>
        </Succeeded></AND></PostCondition><NodeBody>
      <NodeList>
        <Node NodeType="Empty"><NodeId>one</NodeId><Interface><In><DeclareVariable>
                <Name>foo</Name>
                <Type>Integer</Type>
                <InitialValue>
                  <IntegerValue>5</IntegerValue>
                </InitialValue>
              </DeclareVariable></In></Interface><PostCondition><EQNumeric><IntegerVariable>foo</IntegerVariable><IntegerValue>0</IntegerValue></EQNumeric></PostCondition></Node>
        <Node NodeType="Empty"><NodeId>two</NodeId><Interface><In><DeclareVariable>
                <Name>bar</Name>
                <Type>Integer</Type>
                <InitialValue>
                  <IntegerValue>5</IntegerValue>
                </InitialValue>
              </DeclareVariable></In></Interface><PostCondition><EQNumeric><IntegerVariable>bar</IntegerVariable><IntegerValue>5</IntegerValue></EQNumeric></PostCondition></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>