<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><GlobalDeclarations>
    <LibraryNodeDeclaration>
      <Name>library4</Name>
      <Interface/>
    </LibraryNodeDeclaration>
  </GlobalDeclarations><Node NodeType="LibraryNodeCall"><NodeId>root</NodeId><VariableDeclarations>
      <DeclareVariable>
        <Name>name</Name>
        <Type>String</Type>
      </DeclareVariable>
    </VariableDeclarations><NodeBody>
      <LibraryNodeCall>
        <NodeId>library4</NodeId>
      </LibraryNodeCall>
    </NodeBody></Node></PlexilPlan>