<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="Empty"><NodeId>library4</NodeId><Interface><In><DeclareVariable>
          <Name>x</Name>
          <Type>String</Type>
          <InitialValue>
<StringValue>foo</StringValue>
          </InitialValue>
        </DeclareVariable></In></Interface><PostCondition><EQString><StringVariable>x</StringVariable><StringValue>foo</StringValue></EQString></PostCondition></Node></PlexilPlan>