<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="Empty"><NodeId>library1</NodeId><Interface><InOut><DeclareVariable>
          <Name>arg1</Name>
          <Type>Integer</Type>
        </DeclareVariable></InOut></Interface></Node></PlexilPlan>