<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><GlobalDeclarations>
    <LibraryNodeDeclaration>
      <Name>library2</Name>
      <Interface>
        <InOut>
          <DeclareVariable>
            <Name>x</Name>
            <Type>String</Type>
          </DeclareVariable>
        </InOut>
      </Interface>
    </LibraryNodeDeclaration>
  </GlobalDeclarations><Node NodeType="LibraryNodeCall"><NodeId>root</NodeId><VariableDeclarations>
      <DeclareVariable>
        <Name>name</Name>
        <Type>String</Type>
      </DeclareVariable>
    </VariableDeclarations><NodeBody>
      <LibraryNodeCall>
        <NodeId>library2</NodeId>
        <Alias>
          <NodeParameter>x</NodeParameter>
          <StringVariable>name</StringVariable>
        </Alias>
      </LibraryNodeCall>
    </NodeBody></Node></PlexilPlan>