<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="Empty"><NodeId>library5</NodeId><Interface><In><DeclareVariable>
          <Name>x</Name>
          <Type>String</Type>
          <InitialValue>
<StringValue>john</StringValue>
          </InitialValue>
        </DeclareVariable></In></Interface><PostCondition><EQString><StringVariable>x</StringVariable><StringValue>sue</StringValue></EQString></PostCondition></Node></PlexilPlan>