<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="Assignment"><NodeId>library2</NodeId><Interface><InOut><DeclareVariable>
          <Name>x</Name>
          <Type>String</Type>
        </DeclareVariable></InOut></Interface><NodeBody>
      <Assignment>
        <StringVariable>x</StringVariable>
        <StringRHS>
<StringValue>hello</StringValue>
        </StringRHS>
      </Assignment>
    </NodeBody></Node></PlexilPlan>