<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="NodeList"><NodeId>plexilisp_Name_3</NodeId><StartCondition><EQNumeric><IntegerValue>1</IntegerValue><IntegerValue>1</IntegerValue></EQNumeric></StartCondition><NodeBody>
      <NodeList>
        <Node NodeType="Empty"><NodeId>plexilisp_Name_1</NodeId></Node>
        <Node NodeType="Empty"><NodeId>plexilisp_Name_2</NodeId></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>