<?xml version="1.0" encoding="UTF-8"?><!-- Generated by PlexiLisp --><PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tr="extended-plexil-translator"><Node NodeType="NodeList"><NodeId>while_test</NodeId><VariableDeclarations>
      <DeclareVariable>
        <Name>count</Name>
        <Type>Integer</Type>
        <InitialValue>
          <IntegerValue>0</IntegerValue>
        </InitialValue>
      </DeclareVariable>
    </VariableDeclarations><NodeBody>
      <NodeList>
        <Node NodeType="NodeList" epx="While"><NodeId>ep2cp_While_d1e27</NodeId><RepeatCondition><Succeeded><NodeRef dir="child">ep2cp_WhileTest</NodeRef></Succeeded></RepeatCondition><NodeBody><NodeList><Node NodeType="Empty" epx="Condition"><NodeId>ep2cp_WhileTest</NodeId><PostCondition><LT><IntegerVariable>count</IntegerVariable><IntegerValue>2</IntegerValue></LT></PostCondition></Node><Node NodeType="Assignment" epx="Action"><NodeId>plexilisp_Name_1</NodeId><StartCondition><Succeeded><NodeRef dir="sibling">ep2cp_WhileTest</NodeRef></Succeeded></StartCondition><SkipCondition><PostconditionFailed><NodeRef dir="sibling">ep2cp_WhileTest</NodeRef></PostconditionFailed></SkipCondition><NodeBody>
                <Assignment>
                  <IntegerVariable>count</IntegerVariable>
                  <NumericRHS>
                    <ADD>
                      <IntegerVariable>count</IntegerVariable>
                      <IntegerValue>1</IntegerValue>
                    </ADD>
                  </NumericRHS>
                </Assignment>
              </NodeBody></Node></NodeList></NodeBody></Node>
      </NodeList>
    </NodeBody></Node></PlexilPlan>