<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.4 on Mon Aug 13 16:00:00 2007 -->
<PlexilPlan>
 <Node NodeType="Command" >
  <NodeId>Root</NodeId>
  <VariableDeclarations>
      <DeclareVariable>
        <Name>CommandName</Name>
        <Type>String</Type>
        <InitialValue>
          <StringValue>foo</StringValue>
        </InitialValue>
      </DeclareVariable>
  </VariableDeclarations>
  <NodeBody>
   <Command>
    <Name>
     <StringVariable>CommandName</StringVariable>
    </Name>
    <Arguments>
     <StringValue></StringValue>
    </Arguments>
   </Command>
  </NodeBody>
 </Node>
</PlexilPlan>
