#!/bin/bash
# File: $SVNROOT/examples/multi-exec/agents/run-agents

has_xterm=`which xterm`
ipc_running=`ps aux | egrep "ipc|central" | grep -v grep`

if [ -z $1 ] ;
then
  agent1=sim
else
  agent1=$1
fi

if [ -z $2 ] ;
then
  agent2=cmd
else
  agent2=$2
fi

cmd1="plexilexec -v -b -p $agent1.plx -c $agent1.xml"
cmd2="plexilexec -v -b -p $agent2.plx -c $agent2.xml"

if [ "$has_xterm" = "" ] ;
then
  echo " "
  if [ "$ipc_running" = "" ] ;
  then
    echo "ipc (central) must already be running for this script to work without xterm..."
    echo " "
    exit
  else
    echo "xterm not found: both agents will be run in the background..."
    echo " "
  fi
fi

# Try to keep the plans up-to-date
make

# start IPC/central if necessary
if [ "$ipc_running" = "" ] ;
then
  echo "Starting IPC..."
  xterm ipc &
  sleep 2;
else
   echo "IPC already running..."
fi

# Start the agents
echo "Starting $agent1..."
if [ "$has_xterm" = "" ] ;
then
  $cmd1 &
else
  xterm -e $cmd1 &
fi

sleep 10

echo "Starting $agent2..."
if [ "$has_xterm" = "" ] ;
then
  $cmd2
else
  xterm -e $cmd2
fi
