#!/bin/bash
# File: $SVNROOT/examples/multi-exec/agents/run-agents
# Date: Tue Oct 12 17:29:21 2010

has_xterm=`which xterm`

if [ "$has_xterm" = "" ] ;
then
  echo "Sorry, can't run this script without xterms"
  exit
fi

if [ -z $1 ] ;
then
  agent1=sim
else
  agent1=$1
fi

if [ -z $2 ] ;
then
  agent2=cmd
else
  agent2=$2
fi

# compile if necessary

if [ ! -e $agent1.plx ] ;
then
  plexilisp $agent1.pli
fi

if [ ! -e $agent2.plx ] ;
then
  plexilisp $agent2.pli
fi

# start IPC/central if necessary

ipc_running=`ps aux | egrep "ipc|central" | grep -v grep`

if [ "$ipc_running" = "" ] ;
then
   echo "Starting IPC..."
   xterm ipc &
   sleep 2;
else
   echo "IPC already running..."
fi

echo "Starting $agent1..."

xterm -e plexilexec -v -b -p $agent1.plx -c $agent1.xml &

sleep 10

echo "Starting $agent2..."

plexilexec -v -b -p $agent2.plx -c $agent2.xml
