#! /bin/sh
# Install the Python virtual environment for the validator

set -e

# Get Python from environment, if supplied
# Prefer python3 if not
PYTHON=${PYTHON:-"$(command -v python3)"}

if [ -z "$PYTHON" ]
then
    echo 'Error: no Python executable found or supplied.' >&2
    echo 'Set environment variable PYTHON to a Python interpreter' >&2
    echo ' and try again.' >&2
    exit 2
elif [ ! -x "$PYTHON" ]
then
    echo "Error: $PYTHON is not executable." >&2
    echo 'Set environment variable PYTHON to a working Python interpreter' >&2
    echo ' and try again.' >&2
    exit 2
fi

HERE="$( ( cd $(dirname "$0") ; pwd ) )"
VENV_DIR="$HERE/.venv"
PIP="$VENV_DIR/bin/pip"
ACTIVATE="$VENV_DIR/bin/activate"

#
# Start from clean
#

rm -rf "$VENV_DIR" "$HERE/environment"

#
# Bootstrapping
#

echo Initializing Python virtual environment
"$PYTHON" -m venv "$VENV_DIR"

if [ ! -r "$ACTIVATE" ]
then
    echo 'Error: creating Python virtual environment failed.' >&2
    exit 1
fi

( . "$ACTIVATE" && "$PIP" install --upgrade --requirement "$HERE/requirements.txt" )

# Write out environment for validate script
cat << EOF > "$HERE/environment"
# Generated by setup.sh; do not edit
PYTHON='$VENV_DIR/bin/python'
ACTIVATE='$VENV_DIR/bin/activate'
EOF

exit 0
