#! /bin/sh
# Install the Python virtual environment for the validator

set -e

usage()
{
    echo "Usage: $(basename "$0") [ --with-python <PYTHON> ] [ --upgrade ]"
    echo "PYTHON defaults to $(command -v python3)"
    echo 'Requires Python 3.5 or newer'
}

UPGRADE=

while [ -n "$1" ]
do
    case "$1" in
        --with-python)
            shift
            PYTHON="$1"
            ;;

        --upgrade)
            UPGRADE="$1"
            ;;

        -h | --help | help)
            usage
            exit 0
            ;;

        *)
            echo "Error: argument '$1' is not understood" >&2
            usage >&2
            exit 2
            ;;
    esac
    shift
done

# Get Python from environment, if supplied
# Prefer python3 if not
PYTHON=${PYTHON:-"$(command -v python3)"}

if [ -z "$PYTHON" ]
then
    echo 'Error: no Python executable found or supplied.' >&2
    echo 'Please specify a Python 3.5 (or newer) interpreter.' >&2
    exit 2
elif [ ! -x "$PYTHON" ]
then
    echo "Error: $PYTHON is not executable." >&2
    echo 'Try again with a Python 3.5 (or newer) interpreter.' >&2
    exit 2
fi

HERE="$( ( cd $(dirname "$0") ; pwd ) )"
VENV_DIR="$HERE/.venv"
PIP="$VENV_DIR/bin/pip"
ACTIVATE="$VENV_DIR/bin/activate"

#
# Start from clean if not upgrading
#

if [ -z "$UPGRADE" ] && [ -d "$VENV_DIR" ]
then
    echo 'Deleting existing virtual environment'
    rm -rf "$VENV_DIR" "$HERE/environment"
fi

if [ ! -d "$VENV_DIR" ]
then
    echo 'Initializing Python virtual environment'
    if ! "$PYTHON" -m venv "$VENV_DIR"
    then
        echo 'Error: creating Python virtual environment failed.' >&2
        echo 'Check that your Python is version 3.5 or newer.' >&2
        exit 2
    fi
elif [ -n "$UPGRADE" ]
then
    echo 'Upgrading Python virtual environment'
    if ! "$PYTHON" -m venv $UPGRADE "$VENV_DIR"
    then
        echo 'Error: upgrading Python virtual environment failed.' >&2
        exit 2
    fi
fi

if [ ! -r "$ACTIVATE" ]
then
    echo 'Error: Python virtual environment setup failed.' >&2
    exit 1
fi

( . "$ACTIVATE" && \
      "$PIP" install -q -U pip && \
      "$PIP" install -q $UPGRADE -r "$HERE/requirements.txt" )

# Write out environment for validate script
cat << EOF > "$HERE/environment"
# Generated by setup.sh; do not edit
PYTHON='$VENV_DIR/bin/python'
ACTIVATE='$VENV_DIR/bin/activate'
EOF

exit 0
