#! /bin/sh
# Validate PLEXIL files using an XML Schema 1.1 compliant schema

set -e

HERE="$( ( cd $(dirname "$0") ; pwd ) )"

#
# Bootstrapping
#

VENV_DIR="$HERE/.venv"

if [ ! -d "$VENV_DIR" ]
then
    echo 'Setting up validator environment; this will take a moment...'
    "$HERE/setup.sh"
    echo '... done.'
fi

if [ ! -r "$HERE/environment" ]
then
    echo 'Error: setting up validator environment failed.' >&2
    exit 2
fi

# Get the locations of 'activate' and 'python'
. "$HERE/environment"

#
# Now we can do the translation
#

. "$ACTIVATE" && exec "$PYTHON" "$HERE/validate-plexil.py" "$@"
