#! /bin/sh
# Validate PLEXIL files using an XML Schema 1.1 compliant schema

# Copyright (c) 2006-2022, Universities Space Research Association (USRA).
#  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Universities Space Research Association nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e

here="$( cd "$(dirname "$0")" && pwd -P )"

#
# Bootstrapping
#

venv_dir="$here/.venv"

# TEMP DEBUG
# echo "here=$here"
# echo "venv_dir=$venv_dir"

if [ ! -d "$venv_dir" ] || [ ! -r "$here/environment" ]
then
    echo 'Setting up validator environment; this will take a moment...'
    # shellcheck source=setup.sh
    if ! "$here/setup.sh"
    then
       echo 'Error: setting up validator environment failed.' >&2
       exit 1
    fi
    echo '... done.'
fi

# Get the locations of the activate script and python executable
# shellcheck source=environment
. "$here/environment"

# TODO: check that environment is valid!

#
# Now we can do the translation
#

# shellcheck source=.venv/bin/activate
. "$activate_script" && exec "$python_exe" "$here/validate_plexil.py" "$@"
