#! /bin/bash

if [ -z "$1" ]
then
	echo Usage: $0 '[valid-dir]'
	exit 1
fi

for f in ${1}/RUN_*.valid
do
	out=`echo $f | sed -e 's/\.valid/\.stripped/'`
	sed -e 's/id_[0-9]*/id_/g' $f > $out
	echo $out
done