<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PlexiLisp 2.0.5 on Mon Feb 11 15:41:02 2008 -->
<PlexilPlan>
  <Node NodeType="Assignment" >
    <NodeId>Root</NodeId>
    <VariableDeclarations>
      <DeclareVariable>
        <Name>foo</Name>
        <Type>String</Type>
      </DeclareVariable>
      <DeclareVariable>
        <Name>bar</Name>
        <Type>String</Type>
        <InitialValue>
          <StringValue>world</StringValue>
        </InitialValue>
      </DeclareVariable>
    </VariableDeclarations>
    <PostCondition>
      <EQString>
        <StringValue>helloworld</StringValue>
        <StringVariable>foo</StringVariable>
      </EQString>
    </PostCondition>
    <NodeBody>
      <Assignment>
        <StringVariable>foo</StringVariable>
        <StringRHS>
          <Concat>
            <StringValue>hello</StringValue>
            <StringVariable>bar</StringVariable>
          </Concat>
        </StringRHS>
      </Assignment>
    </NodeBody>
  </Node>
</PlexilPlan>
