<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by PlexiLisp 2.0.4 on Wed Jul 18 11:28:55 2007 -->
<PlexilPlan>
  <Node NodeType="Empty">
    <NodeId>Root</NodeId>
    <SkipCondition>
      <BooleanValue>1</BooleanValue>
    </SkipCondition>
  </Node>
</PlexilPlan>
