#! /bin/sh
# Put a Core PLEXIL v1 plan into a canonical format

# Copyright (c) 2006-2022, Universities Space Research Association (USRA).
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Universities Space Research Association nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Use the location of this script to find necessary files.
if [ -z "$PLEXIL_HOME" ]
then
    PLEXIL_HOME="$( cd "$(dirname "$0")"/../.. && pwd -P )"
    export PLEXIL_HOME
fi

if [ $# -lt 1 ] || [ $# -gt 2 ]
then
    echo "Usage: canonicalize input-file [output_file]"
    exit 1
fi

schema_dir="$PLEXIL_HOME"/schema

#
# Options to pass to saxon
# See: https://www.saxonica.com/html/documentation9.9/using-xsl/commandline/
#
#  -config:<file>        - load configuration file
#  -dtd:<on|off|recover> - on = error if input file lacks DTD
#                          off = no checking for DTD
#                          recover = warn if DTD missing
#  -T                    - enable tracing
#  -Tlevel:<level>       - tracing level: none, low, normal, or high
#  -traceout:<file>      - direct tracing output to the named file
#  -TP:<file>            - Write profiling info to an HTML file 
#
xslt_options='-dtd:off'

exec "$PLEXIL_HOME"/scripts/saxon-xslt \
     -xsl:"$schema_dir"/canonicalize-v1.xsl \
     -config:"$schema_dir"/saxon-config.xml $xslt_options \
     -s:"$1" ${2:+-o:"$2"}
