#! /bin/sh

# Copyright (c) 2006-2022, Universities Space Research Association (USRA).
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Universities Space Research Association nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Use the location of this script to find necessary files.
if [ -z "$PLEXIL_HOME" ]
then
    PLEXIL_HOME="$( cd "$(dirname "$0")"/../.. && pwd -P )"
    export PLEXIL_HOME
fi

if [ $# != 1 ]
then
    echo 'Usage: check-plexil-1-2-translation <plx-file>'
    exit 2
fi

# utility locations
schema_dir="$PLEXIL_HOME"/schema
saxon_xslt="$PLEXIL_HOME"/scripts/saxon-xslt
validator="$schema_dir"/validator/validate

outdir="$schema_dir"/test/output

mkdir -p "$outdir"

px1file="$outdir"/"$(basename "$1" .plx)".px1
px2file="$outdir"/"$(basename "$1" .plx)".px2
rm -f "$px2file" "$px1file"

if ! "$saxon_xslt" -xsl:"$schema_dir"/plexil-v1-to-v2.xsl -s:"$1" -o:"$px2file"
then
    echo "*** Translation error converting $(basename "$1") to $(basename "$px2file") ***" >&2
    echo >&2
    exit 1
fi

if ! "$validator" --cache --schema "$schema_dir"/core-plexil-v2.xsd "$px2file"
then
    echo "*** $(basename "$px2file") fails to validate ***" >&2
    echo >&2
    exit 1
fi

if ! "$saxon_xslt" -xsl:"$schema_dir"/plexil-v2-to-v1.xsl -s:"$px2file" -o:"$px1file"
then
    echo "*** Translation error converting $(basename "$px2file") to $(basename "$px1file") ***" >&2
    echo >&2
    exit 1
fi

if ! "$validator" --cache --schema "$schema_dir"/core-plexil.xsd "$px1file"
then
    echo "*** $(basename "$px1file") fails to validate ***" >&2
    echo >&2
    exit 1
fi

canonical_before="$outdir"/"$(basename -s .plx "$1")".canonical.plx
canonical_after="$outdir"/"$(basename -s .plx "$1")".canonical.px1

"$schema_dir"/test/canonicalize "$1" "$canonical_before"
"$schema_dir"/test/canonicalize "$px1file" "$canonical_after"

if ! diff "$canonical_before" "$canonical_after"
then
    echo "*** Files $(basename "$canonical_before") and $(basename "$canonical_after") differ ***" >&2
    echo >&2
    exit 1
fi
