#! /bin/sh
# Test the translation of one Extended Plexil test case
# stdout is presumed to be a log file

# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Universities Space Research Association nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e 

EPLEXIL='../../scripts/eplexil'

# Slower, XML Schema 1.1 capable Python validator
VALIDATE='../validator/validate'
VALIDATE_OPTS='--cache'

# xmllint only supports XML Schema 1.0
#VALIDATE="$(command -v xmllint)"
#VALIDATE_OPTS='--noout --schema ../core-plexil.xsd'


echo "$1"

INPUT="input/$1.epx"
OUTPUT="output/$1.plx"

rm -f "$OUTPUT" "${OUTPUT}.formatted"

if ! "$EPLEXIL" "$INPUT" "$OUTPUT"
then
	test_failed=1
	echo "*** Translation of $INPUT failed ***" >&2
	echo "*** Translation of $INPUT failed ***"
	exit 1
fi

if ! "$VALIDATE" $VALIDATE_OPTS "$OUTPUT"
then
	echo "*** Validation of $1 failed ***" >&2
	echo "*** Validation of $1 failed ***"
    exit 1
elif ! ./check "$1"
then
	echo "*** $OUTPUT failed verification ***" >&2
	echo "*** $OUTPUT failed verification ***"
	xmllint --format "$OUTPUT" > "$OUTPUT.formatted"
    exit 1
fi

printf "%s verifies\n" "$OUTPUT" >&2
exit 0
