#!/bin/sh

# Copyright (c) 2006-2008, Universities Space Research Association (USRA).
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Universities Space Research Association nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# find the location of this script so we can find jar files
# 3 cases:
# - full (possibly relative) path
# - in the current working directory
# - found in $PATH
MYFILE=
if [ -x $0 ] ; then
  # (we think) we have the absolute path
  MYFILE=$0
else
  # use which
  MYFILE=`which $0`
fi
MYDIR=`echo ${MYFILE} | sed -e 's/^[^/\]*$//' -e 's/[/\][^/\]*$//'`
# Special case if script in . and . is in $PATH
if [ -z "${MYDIR}" ]; then
  MYDIR='.'
fi
#echo MYDIR=${MYDIR}

# Pathnames are relative to location of THIS SCRIPT FILE !

if [ $# != 1 ] ; then
  echo "Usage: plexilscript foo-script.ple"
  exit
fi

# echo "Reading:" $1
# echo "Writing:" ${1//\.ple/.plx}

java -cp ${MYDIR}/jars/plexilscript.jar:${MYDIR}/libraries/antlr.jar plexilscript.PlexilScriptParse < $1 > ${1//\.ple/.plx}
