#!/bin/sh

# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Universities Space Research Association nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

if [ -z "$PLEXIL_HOME" ]
then
    echo 'Error: Please set environment variable PLEXIL_HOME'
    echo "to the full pathname of your 'plexil' or 'trunk' directory."
    echo 'Exiting.'
    exit 1
fi

. "$PLEXIL_HOME"/scripts/plexil-setup.sh

ROBOSIM_DIR="$PLEXIL_HOME"/examples/robosim/2DRobotSimulator
ROBOSIM_PROG="$ROBOSIM_DIR"/robotSimulator

usage()
{
    echo "Usage: $(basename "$0") [ start | stop | restart ] [ <robotSimulator options> ]"
    echo ' Script commands:'
    echo '  start   starts up IPC central and the simulator'
    echo '  stop    shuts down the simulator and IPC central'
    echo '  restart shuts down and restarts the simulator (assumes IPC central is running)'
    echo ' With no script command, simply starts robotSimulator with the specified options.'
    echo " Execute '$(basename "$0") -h' to get a list of robotSimulator options."
}

if [ -z "$1" ] || [ '-help' = "$1" ]
then
    usage
    exit 2
fi

plexil_check_prog()
{
    if [ ! -e "$1" ]
    then
        echo "Error: $1 does not exist."
        echo 'You probably need to build it.'
        exit 1
    fi
}

plexil_check_prog "$ROBOSIM_PROG"

# Data files live in this directory
cd "$ROBOSIM_DIR"

if [ "$1" = "start" ]; then
    echo "Starting ipc and simulator..."
    ipc -s -u &
    shift
    "$ROBOSIM_PROG" "$@" &
    sleep 2    
    echo "Done."
elif [ "$1" = "stop" ]; then
    echo "Stoping ipc and simulator..."
    pkill robotSimulator
    pkill central
    echo "Done."
elif [ "$1" = "restart" ]; then
    echo "Restarting simulator..."
    pkill robotSimulator
    shift
    "$ROBOSIM_PROG" "$@" &
    sleep 2
    echo "Done." 
else
    exec "$ROBOSIM_PROG" "$@"
fi
