#!/bin/sh
#
# checksvn: sh script checks for recent svn checkins
#   checks for files with U, P, R, M, C update status
#
#   Argument: relative location of universal_exec root
#
echo "Checking for recent SVN checkins..."

RELDIR=`dirname "$0"`
cd "$RELDIR"
SVNSTATS=`svn -u 2> /dev/null | egrep "^[ADCG]" | cut -d" " -f1`
if [ -n "$SVNSTATS" ]
then 
  echo "***************************************"
  echo "* Warning: Recent SVN checkins found. *"
  echo "***************************************"
else
  echo "No Recent SVN checkins found."
fi
exit 0
