#! /bin/sh

# Copyright (c) 2006-2020, Universities Space Research Association (USRA).
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Universities Space Research Association nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

if [ -z "$PLEXIL_HOME" ]
then
    echo 'Error: Please set environment variable PLEXIL_HOME'
    echo "to the full pathname of your root 'plexil' directory."
    exit 2
fi

if ( echo "$PATH" | grep -q -v "\<$PLEXIL_HOME/scripts\>" )
then
    PATH="$PATH:$PLEXIL_HOME/scripts"
fi

# Select a port range that is not assigned to any particular service.
# See https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml
#min_port=49001
min_port=49100
max_port=49150

# List open Internet sockets to temp file
active_ports="/tmp/find_open_port.$PPID"
port_found=0

ports_in_use="$(list_ports_in_use)"

n=$min_port

while [ $n -le $max_port ]
do
    if echo "$ports_in_use" | grep -q -v "\<$n\>"
    then
        # success
        echo $n
        exit 0
    fi
    n++
done

# not found
exit 1
