#! /usr/bin/env bash

osname=`uname`
if [ "Darwin" = "$osname" ]
then
    # FIXME: sensitive to changes in output format
    netstat -anfinet | grep '^\(tcp\|udp\)' | cut -c22-44 \
        | grep -v '\*\.\*' \
        | sed -e 's/\*\.//g' \
        | sed -E -e 's/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\.//g'
    netstat -anfinet6 | grep '^\(tcp\|udp\)' | cut -c22-44 \
        | grep -v '\*\.\*' \
        | sed -e 's/\*\.//g' \
        | sed -E -e 's/^[0-9a-f:]*(%lo0)?\.//g'
elif [ "Linux" = "$osname" ]
then
    netstat -anAinet | grep '^\(tc\|ud\)p' \
        | sed -e 's/^.*\:\([0-9]\+\) \+[0-9].*$/\1/g'
    netstat -anAinet6 | grep '^\(tc\|ud\)p6' \
        | sed -e 's/^.*\:\([0-9]\+\) \+[0-9\:].*$/\1/g'
else
    echo "Error: Don't know how to get active port list on $osname"
    exit 1
fi
