#! /usr/bin/env bash

osname=`uname`
if [ "Darwin" = "$osname" ]
then
    # FIXME: sensitive to changes in output format
    netstat -anfinet | grep '^\(tc\|ud\)p' \
        | sed -E -e 's/^(tc|ud)p[46]+ +[0-9]+ + [0-9]+ +[0-9\.\*]+\.([0-9]+) +[0-9*].*$/\2/g' \
        | grep -v '\*\.\*'
    netstat -anfinet6 | grep '^\(tc\|ud\)p' \
        | sed -E -e 's/^(tc|ud)p[46]+ +[0-9]+ + [0-9]+ +[0-9A-Fa-flo%\:\*]+\.([0-9]+) +[0-9A-Fa-f\:\*].*$/\2/g' \
        | grep -v '\*\.\*'
elif [ "Linux" = "$osname" ]
then
    netstat -anAinet | grep '^\(tc\|ud\)p' \
        | sed -e 's/^.*\:\([0-9]\+\) \+[0-9].*$/\1/g'
    netstat -anAinet6 | grep '^\(tc\|ud\)p6' \
        | sed -e 's/^.*\:\([0-9]\+\) \+[0-9\:].*$/\1/g'
else
    echo "Error: Don't know how to get active port list on $osname"
    exit 1
fi
