#! /bin/bash

# Copyright (c) 2006-2014, Universities Space Research Association (USRA).
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Universities Space Research Association nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#Validate file
valid()
{
  if [ ! -e $1 ] && [ $quiet = 0 ]
    then
      echo "WARNING: $1 does not exist"
  fi
  return
}

validNum()
{
  if (( ! "$1" > 0 ))
    then    	
  	echo "Error: $1 is not a legal parameter for $2"
	exit 2
  fi
}

warn()
{
   if [ $quiet = 0 ]
     then
       echo "$1"
   fi
}

#There are ranges below 22000 which netstat does not detect
portscan()
{
for((j=65400;j<=65420;++j))
do
if [ "$platform" = "Darwin"  ]
  then
    tport=`netstat -a | grep $j`
  else
    tport=`netstat -l | grep $j`
fi    
    if [ "${tport:-FALSE}" = FALSE ] && [ ! -f /tmp/.Luv_$j ] ; then
    	echo "-n $j"
	return
    fi    
done
return
}
usage="Usage: plexiltest [-p <plan>] [-s] [-v [-h <hostname>] [-n <portnumber>] [-b]] [-d <debug file>] \
[-eprompt] [-wprompt] [-log <log file>] [-ch] [-c <interface config>] [-l <library>]* [-L <library dir>]* \n\n\
For more options enter 'plexiltest -help'"

help="Options:\n\
\n\
 -p | -plan <plan> \n\
\t	specify PLEXIL plan (required) \n\
 -s | -script <script> \n\
\t 	specifies an script file\n\
 -q | -quiet \n\
\t 	suppresses a leading printed summary and default debug messages.\n\
 -v | -viewer \n\
\t 	requests that plan state be transmitted to the Plexil viewer.\n\
 -h | -hostname <name> \n\
\t 	hostname of viewer\n\
 -n | -port <number> \n\
\t 	portnumber of viewer\n\
 -b | -blocking \n\
\t 	enables breakpoints in viewer (recommended)\n\
 -d | -debug <file name> \n\
\t 	debug file (default is Debug.cfg)\n\
 -ch | -check \n\
\t 	runs the PLEXIL static checker prior to executing plan\n\
 -l | -library <file name>\n\
\t 	specifies a plan library (.plx file)\n\
 -L | -libraryPath <directory name>\n\
\t 	specifies a directory for finding plan library files\n\
 -e | -error \n\
 \t	runs debugger if plan hits a c++ error\n\
 -w | -warning \n\
 \t	runs debugger if plan hits a c++ warning\n\
 -? | -help \n\
\t	shows this message of options"
# -a used only for viewer acquire PID

if [ -z "$PLEXIL_HOME" ]
then
    echo Error: Please set environment variable PLEXIL_HOME
    echo to the full pathname of your 'plexil' or 'trunk' directory.
    echo Exiting.
    exit 1
fi

. $PLEXIL_HOME/scripts/plexil-setup.sh

#separate command-line from plexexec output
echo
if [ $PLEXIL_EXECUTABLE ]
then
    prog=$PLEXIL_EXECUTABLE
elif [ -f $PLEXIL_HOME/bin/TestExec ]
then
    prog=$PLEXIL_HOME/bin/TestExec
elif [ -f $PLEXIL_HOME/src/apps/TestExec/TestExec ]
then
    prog=$PLEXIL_HOME/src/apps/TestExec/TestExec
else
    echo "Test Executive executable not found, aborting"
    exit 1
fi

$PLEXIL_HOME/scripts/plexil-check-prog $prog

platform=`uname`
quiet=0
plan_name="" 
plan_cmd="" 
script_name="" 
guess_script=0
script_cmd="" 
libraries="" 
library_dirs=""
debug_file="" 
check="false" 
DEFAULT_PORT=9787
DEFAULT_HOST=127.0.0.1

if [ ! $1 ]
  then
  echo -e $usage
  exit 1
fi

for i in $*
do
    save=$1
    case $1 in
        -quiet | -q ) quiet=1;;
	-p | -plan ) shift
	plan_name=$1
	plan_cmd="-p $1";;
	-s | -script ) shift
	script_name=$1;;
	-l | -library ) shift
	valid $1
	libraries="$libraries -l $1";;
	-L | -libraryPath ) shift
	valid $1	
	library_dirs="$library_dirs -L $1";;
	-d | -debug ) shift
	valid $1
	debug_file="-d $1";;
	-help ) echo -e $help
	  exit 2;;
	-v | -viewer ) viewer="-v";;	#viewer listener enabled	
	-h | -hostname ) shift
	validNum $1 $save
	host_in="-h $1";;	#viewer host name
	-n | -port ) shift
	validNum $1 $save
	port_in="-n $1"
	skip=1;;	#viewer port
	-b | -blocking ) block="-b";;	#enable viewer break point	
	-ch | -check ) check="true";;
	-e | -errors) err="-eprompt";;
	-w | -warnings) warning="-wprompt";;
	-log ) log_file="-log $1";;
	-a ) automate="true";;
	-? ) echo 'Error: missing argument for option' $1
	  echo -e $usage
	  exit 2;;
    esac
    shift
done

# Check if user typed invalid plan
if [ ! -e "$plan_name" ] || [ "$plan_name" = "" ]
  then
        echo Error: Plan $plan_name does not exist.
        exit 1    
fi

#host workaround to skip pass thru check
if [ ! "$host_in" = "" ]
  then
  skip=""
fi

# Check pass thru port into viewer
if [ "$viewer" = "-v" ] && [ "$skip" = "1" ]
  then
  temphelper=$port_in  
  if [ "${port_in//[^0-9]/}" -lt 1024 ] && [ $quiet = 0 ] ; then
    echo "Warning: ${port_in//[^0-9]/} is within frequently used port range, usage of this port is not recommended"
  fi
  if [ "$platform" = "Darwin"  ]
  then
    testOpen=`netstat -a | grep ${temphelper//[^0-9]}`
  else
    testOpen=`netstat -l | grep ${temphelper//[^0-9]}`
  fi
  if [ "$testOpen" = "" ] ; then
      warn "Warning: script may not detect ports listening < 22000"      
    if [ ${temphelper//[^0-9]} -gt 22000 ] ; then
      echo "local Viewer is not listening on ${temphelper//[^0-9]}, exiting"
      exit 1
    fi
  fi
fi

#host re-enable to pass check
if [ ! "$host_in" = "" ]
  then
  skip=1
fi
  
# Check for port number
if [ "$viewer" = "-v" ] ; then
  host=${host_in:="-h $DEFAULT_HOST"}
  port=${port_in:=`portscan`}
    if [ "$port" = "" ] ; then
      echo "Exceeds Maximum number of allowable viewer instances.  Please close
      an instance prior to execution"
      exit 1
  fi
  if [ "$skip" = "" ] ; then
    plexil ${port//[^0-9]/}
    until [ -f /tmp/.Luv_${port//[^0-9]/} ]
      do
	:
    done    
    if [ "$platform" = "Darwin" ] ; then
      sleep 1
    else    
      sleep 1
    fi
  elif [ "$automate" = "" ] ; then
    if [ ! -f /tmp/.Luv_${port//[^0-9]/} ] && [ $quiet = 0 ] ; then
      echo "Warning: Viewer is not listening on port ${port//[^0-9]/}"
    fi
  fi      
fi

if [ ! "$viewer" = "-v" ] && [ "$port_in" ] ; then
  echo "Error: -n option requires Viewer, please add -v option"
  exit 1
fi

# Run default debug
if [ "$debug_file" = "" ] && [ $quiet = 0 ]
  then
    debug_file="-d Debug.cfg"
fi

# Check plan for errors
if [ "$check" = "true" ] && [ -f $PLEXIL_HOME/scripts/checkPlexil ]
  then 
       echo "Checking Plan..."
       $PLEXIL_HOME/scripts/checkPlexil $plan_name
       if [ ! -e "$plan_name" ] && [ $? -gt 0 ]
         then
	   echo Error: $plan_name, contains runtime error
           exit 1
	fi
    elif [ ! -f $PLEXIL_HOME/scripts/checkPlexil ]
      then
	echo Error: $PLEXIL_HOME/scripts/checkPlexil not found.	
	exit 1
fi  

# The plan file's extension, used to compute guessed script name.
ext=".`echo $plan_name | awk -F. '{print $2}'`"

# If no more arguments, or next argument -l, check for candidate scripts.
# Otherwise, next argument must be script.

if [ "$script_name" = "" ]
  then
    guess_script=1
  elif [ ! -e $script_name ]
    then
      echo "Error: Specified script $script_name does not exist!"
      exit 1
fi


if [ $guess_script -eq 1 ]
  then
    script_candidate=`basename $plan_name $ext`.psx
    if [ -e $script_candidate ]
      then
        script_name=$script_candidate
      elif [ -e scripts/$script_candidate ]
        then
          script_name=scripts/$script_candidate
        elif [ -e ../scripts/$script_candidate ]        
          then
            script_name=../scripts/$script_candidate
    fi
fi

if [ "$script_name" = "" ]
  then
    warn "No simulation script specified; using empty script."
    script_name=$PLEXIL_HOME/examples/empty.psx
fi

# Print summary if desired
if [ $quiet -eq 0 ] 
  then
    echo Running executive from $PLEXIL_HOME
    echo "  Plan:      $plan_name"
    echo "  Script:    $script_name"
    echo "  Libraries: $libraries"
    echo "  Library directories: $library_dirs"
    echo "  PORT:      ${port//[^0-9]/}"    
    echo
fi

if [ "$automate" = "true" ]
then    
    echo "RUN_TE_PID$$"
fi
exec $prog $plan_cmd -s $script_name $debug_file $library_dirs $libraries $err $warning $log_file $viewer $host $port $block
