#! /bin/sh 

# Copyright (c) 2006-2022, Universities Space Research Association (USRA).
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Universities Space Research Association nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Use the location of this script to find necessary files.
if [ -z "$PLEXIL_HOME" ]
then
    PLEXIL_HOME="$( cd "$(dirname "$0")"/.. && pwd -P )"
    export PLEXIL_HOME
fi

# Use alternative java runtime if requested
if [ -n "$JAVA_HOME" ]
then
    java_exe="$JAVA_HOME"/bin/java
    if [ ! -f "$java_exe" ]
    then
        echo "$(basename "$0"): Fatal error: no 'java' executable found at $java_exe" >&2
        echo " Check that JAVA_HOME is set correctly." >&2
        exit 1
    elif [ ! -e "$java_exe" ]
    then
        echo "$(basename "$0"): Fatal error: cannot execute $java_exe" >&2
        exit 1
    fi
elif ! java_exe="$(command -v java)"
then
    echo "$(basename "$0"): Fatal error: no 'java' executable found" >&2
    exit 1
fi

jars_dir="$PLEXIL_HOME"/jars
saxon_jar="$jars_dir"/saxon-he-11.4.jar
xmlresolver_jar="$jars_dir"/xmlresolver-4.4.3.jar

exec "$java_exe" -classpath "$saxon_jar":"$xmlresolver_jar" net.sf.saxon.Transform "$@"
