#! /bin/sh

# Generates a concise textual summary of a Core PLEXIL XML file.  

# Copyright (c) 2006-2022, Universities Space Research Association (USRA).
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Universities Space Research Association nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Use the location of this script to find necessary files.
if [ -z "$PLEXIL_HOME" ]
then
    PLEXIL_HOME="$( cd "$(dirname "$0")"/.. && pwd -P )"
    export PLEXIL_HOME
fi

# Defaults

transform_file="$PLEXIL_HOME/schema/summarize-plexil.xsl"
result_file="summary.txt"

usage()
{
    cat <<EOF
Usage: $(basename "$0") input-file [ result-file ] [ transform-file ]"
  result-file defaults to $result_file
  tranform-file defaults to $transform_file
EOF
}
 
# Determine argument values, overriding defaults when specified.

if [ -z "$1" ]
then
    echo "$usage"
    exit 1
fi

input_file="$1"

if [ -n "$2" ]
then
    result_file="$2"
    if [ -n "$3" ]
    then
        transform_file="$3"
    fi
fi

echo "Summarizing $input_file ..."
"${PLEXIL_HOME}/scripts/saxon-xslt" -xsl:"$transform_file" -s:"$input_file" -o:"$result_file"
echo "Summary written to $result_file"
