<?xml version="1.0" encoding="UTF-8"?>
<PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:tr="extended-plexil-translator">
   <Node NodeType="NodeList" epx="Try">
      <NodeId>ep2cp_Try_d1e3</NodeId>
      <VariableDeclarations>
         <DeclareVariable>
            <Name>foo</Name>
            <Type>Integer</Type>
            <InitialValue>
               <IntegerValue>0</IntegerValue>
            </InitialValue>
         </DeclareVariable>
      </VariableDeclarations>
      <EndCondition>
         <OR>
            <EQInternal>
               <NodeOutcomeVariable>
                  <NodeId>One</NodeId>
               </NodeOutcomeVariable>
               <NodeOutcomeValue>SUCCESS</NodeOutcomeValue>
            </EQInternal>
            <EQInternal>
               <NodeOutcomeVariable>
                  <NodeId>ep2cp_Try_d1e29</NodeId>
               </NodeOutcomeVariable>
               <NodeOutcomeValue>SUCCESS</NodeOutcomeValue>
            </EQInternal>
            <EQInternal>
               <NodeOutcomeVariable>
                  <NodeId>Three</NodeId>
               </NodeOutcomeVariable>
               <NodeOutcomeValue>SUCCESS</NodeOutcomeValue>
            </EQInternal>
            <AND>
               <EQInternal>
                  <NodeStateVariable>
                     <NodeId>One</NodeId>
                  </NodeStateVariable>
                  <NodeStateValue>FINISHED</NodeStateValue>
               </EQInternal>
               <EQInternal>
                  <NodeStateVariable>
                     <NodeId>ep2cp_Try_d1e29</NodeId>
                  </NodeStateVariable>
                  <NodeStateValue>FINISHED</NodeStateValue>
               </EQInternal>
               <EQInternal>
                  <NodeStateVariable>
                     <NodeId>Three</NodeId>
                  </NodeStateVariable>
                  <NodeStateValue>FINISHED</NodeStateValue>
               </EQInternal>
            </AND>
         </OR>
      </EndCondition>
      <PostCondition>
         <OR>
            <EQInternal>
               <NodeOutcomeVariable>
                  <NodeId>One</NodeId>
               </NodeOutcomeVariable>
               <NodeOutcomeValue>SUCCESS</NodeOutcomeValue>
            </EQInternal>
            <EQInternal>
               <NodeOutcomeVariable>
                  <NodeId>ep2cp_Try_d1e29</NodeId>
               </NodeOutcomeVariable>
               <NodeOutcomeValue>SUCCESS</NodeOutcomeValue>
            </EQInternal>
            <EQInternal>
               <NodeOutcomeVariable>
                  <NodeId>Three</NodeId>
               </NodeOutcomeVariable>
               <NodeOutcomeValue>SUCCESS</NodeOutcomeValue>
            </EQInternal>
         </OR>
      </PostCondition>
      <NodeBody>
         <NodeList>
            <Node NodeType="Empty">
               <NodeId>One</NodeId>
            </Node>
            <Node NodeType="NodeList" epx="Try">
               <NodeId>ep2cp_Try_d1e29</NodeId>
               <StartCondition>
                  <AND>
                     <EQInternal>
                        <NodeStateVariable>
                           <NodeId>One</NodeId>
                        </NodeStateVariable>
                        <NodeStateValue>FINISHED</NodeStateValue>
                     </EQInternal>
                     <EQNumeric>
                        <IntegerVariable>foo</IntegerVariable>
                        <IntegerValue>0</IntegerValue>
                     </EQNumeric>
                  </AND>
               </StartCondition>
               <PostCondition>
                  <EQInternal>
                     <NodeOutcomeVariable>
                        <NodeId>Two</NodeId>
                     </NodeOutcomeVariable>
                     <NodeOutcomeValue>SUCCESS</NodeOutcomeValue>
                  </EQInternal>
               </PostCondition>
               <NodeBody>
                  <NodeList>
                     <Node NodeType="Empty">
                        <NodeId>Two</NodeId>
                     </Node>
                  </NodeList>
               </NodeBody>
            </Node>
            <Node NodeType="Empty">
               <NodeId>Three</NodeId>
               <StartCondition>
                  <EQInternal>
                     <NodeStateVariable>
                        <NodeId>ep2cp_Try_d1e29</NodeId>
                     </NodeStateVariable>
                     <NodeStateValue>FINISHED</NodeStateValue>
                  </EQInternal>
               </StartCondition>
            </Node>
         </NodeList>
      </NodeBody>
   </Node>
</PlexilPlan>