<?xml version="1.0" encoding="UTF-8"?>
<PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:tr="extended-plexil-translator">
   <Node NodeType="NodeList" epx="Sequence">
      <NodeId>ep2cp_Sequence_d1e3</NodeId>
      <VariableDeclarations>
         <DeclareVariable>
            <Name>x</Name>
            <Type>Real</Type>
            <InitialValue>
               <RealValue>100.3</RealValue>
            </InitialValue>
         </DeclareVariable>
      </VariableDeclarations>
      <InvariantCondition>
         <AND>
            <NOT>
               <OR>
                  <EQInternal>
                     <NodeOutcomeVariable>
                        <NodeId>Wait1</NodeId>
                     </NodeOutcomeVariable>
                     <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                  </EQInternal>
                  <EQInternal>
                     <NodeOutcomeVariable>
                        <NodeId>Wait2</NodeId>
                     </NodeOutcomeVariable>
                     <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                  </EQInternal>
               </OR>
            </NOT>
         </AND>
      </InvariantCondition>
      <NodeBody>
         <NodeList>
            <Node NodeType="Empty" epx="Wait" FileName="foo.ple" LineNo="104" ColNo="1">
               <NodeId>Wait1</NodeId>
               <EndCondition>
                  <OR>
                     <GE>
                        <LookupOnChange>
                           <Name>
                              <StringValue>time</StringValue>
                           </Name>
                           <Tolerance>
                              <RealValue>0.2</RealValue>
                           </Tolerance>
                        </LookupOnChange>
                        <ADD>
                           <RealValue>23.9</RealValue>
                           <NodeTimepointValue>
                              <NodeId>Wait1</NodeId>
                              <NodeStateValue>EXECUTING</NodeStateValue>
                              <Timepoint>START</Timepoint>
                           </NodeTimepointValue>
                        </ADD>
                     </GE>
                  </OR>
               </EndCondition>
            </Node>
            <Node NodeType="Empty" epx="Wait" FileName="foo.ple" LineNo="108" ColNo="1">
               <NodeId>Wait2</NodeId>
               <StartCondition>
                  <AND>
                     <EQInternal>
                        <NodeStateVariable>
                           <NodeId>Wait1</NodeId>
                        </NodeStateVariable>
                        <NodeStateValue>FINISHED</NodeStateValue>
                     </EQInternal>
                  </AND>
               </StartCondition>
               <EndCondition>
                  <OR>
                     <GE>
                        <LookupOnChange>
                           <Name>
                              <StringValue>time</StringValue>
                           </Name>
                           <Tolerance>
                              <RealValue>1.0</RealValue>
                           </Tolerance>
                        </LookupOnChange>
                        <ADD>
                           <RealVariable>x</RealVariable>
                           <NodeTimepointValue>
                              <NodeId>Wait2</NodeId>
                              <NodeStateValue>EXECUTING</NodeStateValue>
                              <Timepoint>START</Timepoint>
                           </NodeTimepointValue>
                        </ADD>
                     </GE>
                  </OR>
               </EndCondition>
            </Node>
         </NodeList>
      </NodeBody>
   </Node>
</PlexilPlan>