<?xml version="1.0" encoding="UTF-8"?>
<PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:tr="extended-plexil-translator">
   <Node NodeType="NodeList" epx="Sequence" FileName="While4.ple" LineNo="2" ColNo="1">
      <NodeId>testwhile</NodeId>
      <VariableDeclarations>
              <DeclareVariable>
                  <Name>distance</Name>
                  <Type>Integer</Type>
                  <InitialValue>
                      <IntegerValue>5</IntegerValue>
                  </InitialValue>
              </DeclareVariable>
          </VariableDeclarations>
      <InvariantCondition>
         <AND>
            <NOT>
               <OR>
                  <EQInternal>
                     <NodeOutcomeVariable>
                        <NodeId>Enter</NodeId>
                     </NodeOutcomeVariable>
                     <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                  </EQInternal>
                  <EQInternal>
                     <NodeOutcomeVariable>
                        <NodeId>Advance</NodeId>
                     </NodeOutcomeVariable>
                     <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                  </EQInternal>
               </OR>
            </NOT>
         </AND>
      </InvariantCondition>
      <NodeBody>
         <NodeList>
            <Node NodeType="Assignment" FileName="While4.ple" LineNo="8" ColNo="5">
               <NodeId>Enter</NodeId>
               <NodeBody>
                  <Assignment>
                      <IntegerVariable>distance</IntegerVariable>
                      <NumericRHS>
                          <IntegerValue>3</IntegerValue>
                      </NumericRHS>
                  </Assignment>
              </NodeBody>
            </Node>
            <Node NodeType="NodeList" epx="While" FileName="While4.ple" LineNo="13" ColNo="5">
               <NodeId>Advance</NodeId>
               <VariableDeclarations>
                  <DeclareVariable>
                     <Name>ep2cp_test</Name>
                     <Type>Boolean</Type>
                  </DeclareVariable>
               </VariableDeclarations>
               <StartCondition>
                  <AND>
                     <EQInternal>
                        <NodeStateVariable>
                           <NodeId>Enter</NodeId>
                        </NodeStateVariable>
                        <NodeStateValue>FINISHED</NodeStateValue>
                     </EQInternal>
                  </AND>
               </StartCondition>
               <NodeBody>
                  <NodeList>
                     <Node NodeType="NodeList" epx="aux">
                        <NodeId>ep2cp_WhileBody</NodeId>
                        <NodeBody>
                           <NodeList>
                              <Node NodeType="Assignment" epx="aux">
                                 <NodeId>ep2cp_WhileSetup</NodeId>
                                 <NodeBody>
                                    <Assignment>
                                       <BooleanVariable>ep2cp_test</BooleanVariable>
                                       <BooleanRHS>
                                          <GT>
                                             <IntegerVariable>distance</IntegerVariable>
                                             <IntegerValue>0</IntegerValue>
                                          </GT>
                                       </BooleanRHS>
                                    </Assignment>
                                 </NodeBody>
                              </Node>
                              <Node NodeType="NodeList" epx="aux">
                                 <NodeId>ep2cp_WhileTrue</NodeId>
                                 <StartCondition>
                                    <AND>
                                       <EQInternal>
                                          <NodeStateVariable>
                                             <NodeId>ep2cp_WhileSetup</NodeId>
                                          </NodeStateVariable>
                                          <NodeStateValue>FINISHED</NodeStateValue>
                                       </EQInternal>
                                       <BooleanVariable>ep2cp_test</BooleanVariable>
                                    </AND>
                                 </StartCondition>
                                 <SkipCondition>
                                    <AND>
                                       <EQInternal>
                                          <NodeStateVariable>
                                             <NodeId>ep2cp_WhileSetup</NodeId>
                                          </NodeStateVariable>
                                          <NodeStateValue>FINISHED</NodeStateValue>
                                       </EQInternal>
                                       <NOT>
                                          <BooleanVariable>ep2cp_test</BooleanVariable>
                                       </NOT>
                                    </AND>
                                 </SkipCondition>
                                 <RepeatCondition>
                                    <BooleanVariable>ep2cp_test</BooleanVariable>
                                 </RepeatCondition>
                                 <NodeBody>
                                    <NodeList>
                                       <Node NodeType="NodeList" epx="aux">
                                          <NodeId>ep2cp_WhileAction</NodeId>
                                          <NodeBody>
                                             <NodeList>
                                                <Node NodeType="Assignment" FileName="While4.ple" LineNo="15" ColNo="7">
                                                   <NodeId>Advance__CHILD__1</NodeId>
                                                   <NodeBody>
                                                      <Assignment>
                                                         <IntegerVariable>distance</IntegerVariable>
                                                         <NumericRHS>
                                                            <SUB>
                                                               <IntegerVariable>distance</IntegerVariable>
                                                               <IntegerValue>1</IntegerValue>
                                                            </SUB>
                                                         </NumericRHS>
                                                      </Assignment>
                                                   </NodeBody>
                                                </Node>
                                             </NodeList>
                                          </NodeBody>
                                       </Node>
                                       <Node NodeType="Assignment" epx="aux">
                                          <NodeId>ep2cp_WhileRetest</NodeId>
                                          <StartCondition>
                                             <EQInternal>
                                                <NodeStateVariable>
                                                   <NodeId>ep2cp_WhileAction</NodeId>
                                                </NodeStateVariable>
                                                <NodeStateValue>FINISHED</NodeStateValue>
                                             </EQInternal>
                                          </StartCondition>
                                          <NodeBody>
                                             <Assignment>
                                                <BooleanVariable>ep2cp_test</BooleanVariable>
                                                <BooleanRHS>
                                                   <GT>
                                                      <IntegerVariable>distance</IntegerVariable>
                                                      <IntegerValue>0</IntegerValue>
                                                   </GT>
                                                </BooleanRHS>
                                             </Assignment>
                                          </NodeBody>
                                       </Node>
                                    </NodeList>
                                 </NodeBody>
                              </Node>
                           </NodeList>
                        </NodeBody>
                     </Node>
                  </NodeList>
               </NodeBody>
            </Node>
         </NodeList>
      </NodeBody>
   </Node>
</PlexilPlan>