#! /bin/sh

# Copyright (c) 2006-2022, Universities Space Research Association (USRA).
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Universities Space Research Association nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY USRA ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL USRA BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

if [ -z "$PLEXIL_HOME" ]
then
    # Derive PLEXIL_HOME from $0
    PLEXIL_HOME="$(cd "$(dirname "$0")" ; cd ../.. ; pwd)"
    export PLEXIL_HOME
fi

. "$PLEXIL_HOME"/scripts/plexil-setup.sh

JARS_DIR="${PLEXIL_HOME}/jars"
PLEXIL_COMPILER_JAR="${JARS_DIR}/PlexilCompiler.jar"
ANTLR_RUNTIME_JAR="${JARS_DIR}/antlr-3.5.3-complete-no-st3.jar"
SAXON_HE_JAR="${JARS_DIR}/saxon-he-11.4.jar"
XMLRESOLVER_JAR="${JARS_DIR}/xmlresolver-4.4.3.jar"
JAVA="$(command -v java)"
if [ -n "$JAVA_HOME" ]
then
    JAVA="$JAVA_HOME"/bin/java
fi

exec "$JAVA" \
     -classpath "${PLEXIL_COMPILER_JAR}:${ANTLR_RUNTIME_JAR}:${SAXON_HE_JAR}:${XMLRESOLVER_JAR}" \
     plexil.Compiler "$@"
