<?xml version="1.0" encoding="UTF-8"?>
<PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:tr="extended-plexil-translator">
   <Node NodeType="NodeList" epx="Sequence" FileName="sas-test.ple" LineNo="4" ColNo="1">
      <NodeId>Root</NodeId>
      <VariableDeclarations>
              <DeclareVariable>
                  <Name>rightIter</Name>
                  <Type>Integer</Type>
                  <InitialValue>
                      <IntegerValue>4</IntegerValue>
                  </InitialValue>
              </DeclareVariable>
              <DeclareVariable>
                  <Name>x</Name>
                  <Type>Integer</Type>
                  <InitialValue>
                      <IntegerValue>0</IntegerValue>
                  </InitialValue>
              </DeclareVariable>
          </VariableDeclarations>
      <StartCondition>
         <GT>
            <LookupOnChange>
                      <Name>
                          <StringValue>x</StringValue>
                      </Name>
                  </LookupOnChange>
            <IntegerValue>10</IntegerValue>
         </GT>
      </StartCondition>
      <InvariantCondition>
         <AND>
            <LE>
               <IntegerVariable>x</IntegerVariable>
               <IntegerValue>21</IntegerValue>
            </LE>
            <NOT>
               <OR>
                  <EQInternal>
                     <NodeOutcomeVariable>
                        <NodeId>Body</NodeId>
                     </NodeOutcomeVariable>
                     <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                  </EQInternal>
                  <EQInternal>
                     <NodeOutcomeVariable>
                        <NodeId>Quit</NodeId>
                     </NodeOutcomeVariable>
                     <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                  </EQInternal>
               </OR>
            </NOT>
         </AND>
      </InvariantCondition>
      <NodeBody>
         <NodeList>
            <Node NodeType="NodeList" FileName="sas-test.ple" LineNo="11" ColNo="17">
               <NodeId>Body</NodeId>
               <NodeBody>
                  <NodeList>
                      <Node NodeType="NodeList" epx="Sequence" FileName="sas-test.ple" LineNo="14"
                           ColNo="25">
                        <NodeId>Right</NodeId>
                        <VariableDeclarations>
                              <DeclareVariable>
                                  <Name>new_x</Name>
                                  <Type>Integer</Type>
                              </DeclareVariable>
                          </VariableDeclarations>
                        <RepeatCondition>
                           <GT>
                              <IntegerVariable>rightIter</IntegerVariable>
                              <IntegerValue>0</IntegerValue>
                           </GT>
                        </RepeatCondition>
                        <InvariantCondition>
                           <AND>
                              <NOT>
                                 <OR>
                                    <EQInternal>
                                       <NodeOutcomeVariable>
                                          <NodeId>Action</NodeId>
                                       </NodeOutcomeVariable>
                                       <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                                    </EQInternal>
                                    <EQInternal>
                                       <NodeOutcomeVariable>
                                          <NodeId>SetX</NodeId>
                                       </NodeOutcomeVariable>
                                       <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                                    </EQInternal>
                                    <EQInternal>
                                       <NodeOutcomeVariable>
                                          <NodeId>Set</NodeId>
                                       </NodeOutcomeVariable>
                                       <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                                    </EQInternal>
                                 </OR>
                              </NOT>
                           </AND>
                        </InvariantCondition>
                        <NodeBody>
                           <NodeList>
                              <Node NodeType="Command" FileName="sas-test.ple" LineNo="19" ColNo="33">
                                 <NodeId>Action</NodeId>
                                 <EndCondition>
                                    <IsKnown>
                                       <IntegerVariable>new_x</IntegerVariable>
                                    </IsKnown>
                                 </EndCondition>
                                 <NodeBody>
                                    <Command>
                                      <IntegerVariable>new_x</IntegerVariable>
                                      <Name>
                                          <StringValue>MoveRight</StringValue>
                                      </Name>
                                      <Arguments>
                                          <IntegerValue>5</IntegerValue>
                                      </Arguments>
                                    </Command>
                                 </NodeBody>
                              </Node>
                              <Node NodeType="Assignment" FileName="sas-test.ple" LineNo="24" ColNo="33">
                                 <NodeId>SetX</NodeId>
                                 <StartCondition>
                                    <AND>
                                       <EQInternal>
                                          <NodeStateVariable>
                                             <NodeId>Action</NodeId>
                                          </NodeStateVariable>
                                          <NodeStateValue>FINISHED</NodeStateValue>
                                       </EQInternal>
                                    </AND>
                                 </StartCondition>
                                 <NodeBody>
                                    <Assignment>
                                      <IntegerVariable>x</IntegerVariable>
                                      <NumericRHS>
                                          <IntegerVariable>new_x</IntegerVariable>
                                      </NumericRHS>
                                    </Assignment>
                                 </NodeBody>
                              </Node>
                              <Node NodeType="Assignment" FileName="sas-test.ple" LineNo="28" ColNo="33">
                                 <NodeId>Set</NodeId>
                                 <StartCondition>
                                    <AND>
                                       <EQInternal>
                                          <NodeStateVariable>
                                             <NodeId>SetX</NodeId>
                                          </NodeStateVariable>
                                          <NodeStateValue>FINISHED</NodeStateValue>
                                       </EQInternal>
                                    </AND>
                                 </StartCondition>
                                 <NodeBody>
                                    <Assignment>
                                      <IntegerVariable>rightIter</IntegerVariable>
                                      <NumericRHS>
                                          <SUB>
                                              <IntegerVariable>rightIter</IntegerVariable>
                                              <IntegerValue>1</IntegerValue>
                                          </SUB>
                                      </NumericRHS>
                                    </Assignment>
                                 </NodeBody>
                              </Node>
                           </NodeList>
                        </NodeBody>
                     </Node>
                  </NodeList>
              </NodeBody>
            </Node>
            <Node NodeType="Command" FileName="sas-test.ple" LineNo="34" ColNo="17">
               <NodeId>Quit</NodeId>
               <StartCondition>
                  <AND>
                     <EQInternal>
                        <NodeStateVariable>
                           <NodeId>Body</NodeId>
                        </NodeStateVariable>
                        <NodeStateValue>FINISHED</NodeStateValue>
                     </EQInternal>
                  </AND>
               </StartCondition>
               <NodeBody>
                  <Command>
                      <Name>
                          <StringValue>SendMessage</StringValue>
                      </Name>
                      <Arguments>
                          <StringValue>Quit</StringValue>
                      </Arguments>
                  </Command>
              </NodeBody>
            </Node>
         </NodeList>
      </NodeBody>
   </Node>
</PlexilPlan>