  <PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://plexil.svn.sourceforge.net/viewvc/plexil/trunk/schema/supported-plexil.xsd" FileName="plans/test.ple">
      <GlobalDeclarations>
          <CommandDeclaration>
              <Name>TakePicture</Name>
              <Return Type="Boolean">_Command_return_1</Return>
              <Parameter Type="Integer">_Command_param_1</Parameter>
              <Parameter Type="Integer">_Command_param_2</Parameter>
              <Parameter Type="Real">_Command_param_3</Parameter>
          </CommandDeclaration>
          <CommandDeclaration>
              <Name>Drive</Name>
              <Parameter Type="Integer">_Command_param_1</Parameter>
              <Parameter Type="Boolean">_Command_param_2</Parameter>
              <Parameter Type="Real">_Command_param_3</Parameter>
              <Parameter Type="String">_Command_param_4</Parameter>
          </CommandDeclaration>
          <StateDeclaration>
              <Name>X</Name>
              <Return Type="Boolean">_State_return_1</Return>
          </StateDeclaration>
      </GlobalDeclarations>
      <Node NodeType="NodeList" FileName="plans/test.ple" LineNo="9" ColNo="1">
          <VariableDeclarations>
              <DeclareVariable>
                  <Name>i</Name>
                  <Type>Integer</Type>
                  <InitialValue>
                      <IntegerValue>5</IntegerValue>
                  </InitialValue>
              </DeclareVariable>
              <DeclareVariable>
                  <Name>b</Name>
                  <Type>Boolean</Type>
                  <InitialValue>
                      <BooleanValue>true</BooleanValue>
                  </InitialValue>
              </DeclareVariable>
              <DeclareArray>
                  <Name>j</Name>
                  <Type>Integer</Type>
                  <MaxSize>4</MaxSize>
                  <InitialValue>
                      <IntegerValue>5</IntegerValue>
                  </InitialValue>
              </DeclareArray>
          </VariableDeclarations>
          <NodeId>ListNode</NodeId>
          <StartCondition>
              <EQInternal>
                  <NodeStateVariable>
                      <NodeId>ANode</NodeId>
                  </NodeStateVariable>
                  <NodeStateValue>FINISHED</NodeStateValue>
              </EQInternal>
          </StartCondition>
          <EndCondition>
              <LE>
                  <IntegerVariable>i</IntegerVariable>
                  <IntegerValue>7</IntegerValue>
              </LE>
          </EndCondition>
          <RepeatCondition>
              <NENumeric>
                  <IntegerVariable>i</IntegerVariable>
                  <IntegerValue>5</IntegerValue>
              </NENumeric>
          </RepeatCondition>
          <InvariantCondition>
              <OR>
                  <AND>
                      <NOT>
                          <BooleanVariable>b</BooleanVariable>
                      </NOT>
                      <IsKnown>
                          <IntegerVariable>i</IntegerVariable>
                      </IsKnown>
                  </AND>
                  <BooleanValue>false</BooleanValue>
              </OR>
          </InvariantCondition>
          <PreCondition>
              <EQString>
                  <StringValue>hi</StringValue>
                  <Concat>
                      <StringValue>h</StringValue>
                      <StringValue>i</StringValue>
                  </Concat>
              </EQString>
          </PreCondition>
          <PostCondition>
              <NEBoolean>
                  <BooleanValue>true</BooleanValue>
                  <EQBoolean>
                      <BooleanValue>false</BooleanValue>
                      <BooleanValue>true</BooleanValue>
                  </EQBoolean>
              </NEBoolean>
          </PostCondition>
          <SkipCondition>
              <OR>
                  <OR>
                      <EQInternal>
                          <NodeStateValue>WAITING</NodeStateValue>
                          <NodeStateValue>FAILING</NodeStateValue>
                      </EQInternal>
                      <EQInternal>
                          <NodeStateValue>ITERATION_ENDED</NodeStateValue>
                          <NodeStateValue>INACTIVE</NodeStateValue>
                      </EQInternal>
                  </OR>
                  <EQInternal>
                      <NodeStateValue>EXECUTING</NodeStateValue>
                      <NodeStateValue>FINISHING</NodeStateValue>
                  </EQInternal>
              </OR>
          </SkipCondition>
          <NodeBody>
              <NodeList>
                  <Node NodeType="Assignment" FileName="plans/test.ple" LineNo="26" ColNo="3">
                      <NodeId>ANode</NodeId>
                      <StartCondition>
                          <GT>
                              <ArrayElement>
                                  <Name>j</Name>
                                  <Index>
                                      <IntegerValue>1</IntegerValue>
                                  </Index>
                              </ArrayElement>
                              <IntegerValue>3</IntegerValue>
                          </GT>
                      </StartCondition>
                      <NodeBody>
                          <Assignment>
                              <ArrayElement>
                                  <Name>j</Name>
                                  <Index>
                                      <IntegerValue>2</IntegerValue>
                                  </Index>
                              </ArrayElement>
                              <NumericRHS>
                                  <SUB>
                                      <ADD>
                                          <IntegerValue>3</IntegerValue>
                                          <MUL>
                                              <IntegerValue>2</IntegerValue>
                                              <IntegerValue>1</IntegerValue>
                                          </MUL>
                                      </ADD>
                                      <DIV>
                                          <IntegerValue>5</IntegerValue>
                                          <SQRT>
                                              <ABS>
                                                  <IntegerValue>7</IntegerValue>
                                              </ABS>
                                          </SQRT>
                                      </DIV>
                                  </SUB>
                              </NumericRHS>
                          </Assignment>
                      </NodeBody>
                  </Node>
                  <Node NodeType="Command" FileName="plans/test.ple" LineNo="31" ColNo="3">
                      <NodeId>CNode</NodeId>
                      <StartCondition>
                          <LookupOnChange>
                              <Name>
                                  <StringValue>X</StringValue>
                              </Name>
                          </LookupOnChange>
                      </StartCondition>
                      <NodeBody>
                          <Command>
                              <Name>
                                  <StringValue>Drive</StringValue>
                              </Name>
                              <Arguments>
                                  <IntegerValue>1</IntegerValue>
                                  <BooleanValue>false</BooleanValue>
                                  <RealValue>1.53</RealValue>
                                  <StringValue>31</StringValue>
                              </Arguments>
                          </Command>
                      </NodeBody>
                  </Node>
                  <Node NodeType="LibraryNodeCall" FileName="plans/test.ple" LineNo="36" ColNo="3">
                      <NodeId>LNode</NodeId>
                      <NodeBody>
                          <LibraryNodeCall>
                              <NodeId>LibTest</NodeId>
                              <Alias>
                                  <NodeParameter>i</NodeParameter>
                                  <IntegerVariable>i</IntegerVariable>
                              </Alias>
                              <Alias>
                                  <NodeParameter>s</NodeParameter>
                                  <StringValue>4</StringValue>
                              </Alias>
                          </LibraryNodeCall>
                      </NodeBody>
                  </Node>
                  <Node NodeType="Empty" FileName="plans/test.ple" LineNo="40" ColNo="3">
                      <NodeId>ListNode__CHILD__4</NodeId>
                  </Node>
              </NodeList>
          </NodeBody>
      </Node>
  </PlexilPlan>
