<?xml version="1.0" encoding="UTF-8"?>
<PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:tr="extended-plexil-translator">
   <GlobalDeclarations LineNo="5" ColNo="5">
      <StateDeclaration LineNo="5" ColNo="5">
         <Name>time</Name>
         <Return>
            <Name>_return_0</Name>
            <Type>Real</Type>
         </Return>
      </StateDeclaration>
   </GlobalDeclarations>
   <Node NodeType="NodeList" epx="Sequence" LineNo="9" ColNo="2">
      <NodeId>Root</NodeId>
      <VariableDeclarations>
         <DeclareVariable LineNo="9" ColNo="2">
            <Name>x</Name>
            <Type>Integer</Type>
            <InitialValue>
               <IntegerValue>0</IntegerValue>
            </InitialValue>
         </DeclareVariable>
         <DeclareVariable LineNo="9" ColNo="2">
            <Name>y</Name>
            <Type>Integer</Type>
            <InitialValue>
               <IntegerValue>0</IntegerValue>
            </InitialValue>
         </DeclareVariable>
         <DeclareVariable LineNo="10" ColNo="2">
            <Name>thresh</Name>
            <Type>Real</Type>
            <InitialValue>
               <RealValue>0.1</RealValue>
            </InitialValue>
         </DeclareVariable>
      </VariableDeclarations>
      <InvariantCondition>
         <AND>
            <NOT>
               <OR>
                  <EQInternal>
                     <NodeOutcomeVariable>
                        <NodeId>Activity1</NodeId>
                     </NodeOutcomeVariable>
                     <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                  </EQInternal>
                  <EQInternal>
                     <NodeOutcomeVariable>
                        <NodeId>Activity2</NodeId>
                     </NodeOutcomeVariable>
                     <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                  </EQInternal>
                  <EQInternal>
                     <NodeOutcomeVariable>
                        <NodeId>Sub</NodeId>
                     </NodeOutcomeVariable>
                     <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                  </EQInternal>
                  <EQInternal>
                     <NodeOutcomeVariable>
                        <NodeId>Activity5</NodeId>
                     </NodeOutcomeVariable>
                     <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                  </EQInternal>
               </OR>
            </NOT>
         </AND>
      </InvariantCondition>
      <NodeBody>
         <NodeList>
            <Node NodeType="Assignment" LineNo="14" ColNo="4">
               <NodeId>Activity1</NodeId>
               <NodeBody>
                  <Assignment>
                     <IntegerVariable>x</IntegerVariable>
                     <NumericRHS>
                        <IntegerValue>1</IntegerValue>
                     </NumericRHS>
                  </Assignment>
               </NodeBody>
            </Node>
            <Node NodeType="Assignment" LineNo="20" ColNo="4">
               <NodeId>Activity2</NodeId>
               <StartCondition>
                  <AND>
                     <EQInternal>
                        <NodeStateVariable>
                           <NodeId>Activity1</NodeId>
                        </NodeStateVariable>
                        <NodeStateValue>FINISHED</NodeStateValue>
                     </EQInternal>
                  </AND>
               </StartCondition>
               <EndCondition>
                  <GE>
                     <LookupOnChange>
                        <Name>
                           <StringValue>time</StringValue>
                        </Name>
                        <Tolerance>
                           <RealVariable>thresh</RealVariable>
                        </Tolerance>
                     </LookupOnChange>
                     <ADD LineNo="19" ColNo="56">
                        <NodeTimepointValue>
                           <NodeId>Activity1</NodeId>
                           <NodeStateValue>FINISHED</NodeStateValue>
                           <Timepoint>START</Timepoint>
                        </NodeTimepointValue>
                        <RealValue>1.0</RealValue>
                     </ADD>
                  </GE>
               </EndCondition>
               <NodeBody>
                  <Assignment>
                     <IntegerVariable>x</IntegerVariable>
                     <NumericRHS>
                        <IntegerValue>2</IntegerValue>
                     </NumericRHS>
                  </Assignment>
               </NodeBody>
            </Node>
            <Node NodeType="NodeList" epx="Concurrence" LineNo="23" ColNo="8">
               <NodeId>Sub</NodeId>
               <StartCondition>
                  <AND>
                     <EQInternal>
                        <NodeStateVariable>
                           <NodeId>Activity2</NodeId>
                        </NodeStateVariable>
                        <NodeStateValue>FINISHED</NodeStateValue>
                     </EQInternal>
                  </AND>
               </StartCondition>
               <EndCondition>
                  <GE>
                     <LookupOnChange>
                        <Name>
                           <StringValue>time</StringValue>
                        </Name>
                        <Tolerance>
                           <RealVariable>thresh</RealVariable>
                        </Tolerance>
                     </LookupOnChange>
                     <ADD LineNo="25" ColNo="56">
                        <NodeTimepointValue>
                           <NodeId>Activity2</NodeId>
                           <NodeStateValue>FINISHED</NodeStateValue>
                           <Timepoint>START</Timepoint>
                        </NodeTimepointValue>
                        <RealValue>1.0</RealValue>
                     </ADD>
                  </GE>
               </EndCondition>
               <NodeBody>
                  <NodeList>
                     <Node NodeType="Assignment" LineNo="29" ColNo="6">
                        <NodeId>Activity3</NodeId>
                        <EndCondition>
                           <GE>
                              <LookupOnChange>
                                 <Name>
                                    <StringValue>time</StringValue>
                                 </Name>
                                 <Tolerance>
                                    <RealVariable>thresh</RealVariable>
                                 </Tolerance>
                              </LookupOnChange>
                              <ADD LineNo="28" ColNo="59">
                                 <NodeTimepointValue>
                                    <NodeId>Activity3</NodeId>
                                    <NodeStateValue>EXECUTING</NodeStateValue>
                                    <Timepoint>START</Timepoint>
                                 </NodeTimepointValue>
                                 <RealValue>1.0</RealValue>
                              </ADD>
                           </GE>
                        </EndCondition>
                        <NodeBody>
                           <Assignment>
                              <IntegerVariable>x</IntegerVariable>
                              <NumericRHS>
                                 <IntegerValue>3</IntegerValue>
                              </NumericRHS>
                           </Assignment>
                        </NodeBody>
                     </Node>
                     <Node NodeType="Assignment" LineNo="35" ColNo="6">
                        <NodeId>Activity4</NodeId>
                        <EndCondition>
                           <GE>
                              <LookupOnChange>
                                 <Name>
                                    <StringValue>time</StringValue>
                                 </Name>
                                 <Tolerance>
                                    <RealVariable>thresh</RealVariable>
                                 </Tolerance>
                              </LookupOnChange>
                              <ADD LineNo="34" ColNo="59">
                                 <NodeTimepointValue>
                                    <NodeId>Activity4</NodeId>
                                    <NodeStateValue>EXECUTING</NodeStateValue>
                                    <Timepoint>START</Timepoint>
                                 </NodeTimepointValue>
                                 <RealValue>1.0</RealValue>
                              </ADD>
                           </GE>
                        </EndCondition>
                        <NodeBody>
                           <Assignment>
                              <IntegerVariable>y</IntegerVariable>
                              <NumericRHS>
                                 <IntegerValue>4</IntegerValue>
                              </NumericRHS>
                           </Assignment>
                        </NodeBody>
                     </Node>
                  </NodeList>
               </NodeBody>
            </Node>
            <Node NodeType="Assignment" LineNo="42" ColNo="4">
               <NodeId>Activity5</NodeId>
               <StartCondition>
                  <AND>
                     <EQInternal>
                        <NodeStateVariable>
                           <NodeId>Sub</NodeId>
                        </NodeStateVariable>
                        <NodeStateValue>FINISHED</NodeStateValue>
                     </EQInternal>
                  </AND>
               </StartCondition>
               <EndCondition>
                  <GE>
                     <LookupOnChange>
                        <Name>
                           <StringValue>time</StringValue>
                        </Name>
                        <Tolerance>
                           <RealVariable>thresh</RealVariable>
                        </Tolerance>
                     </LookupOnChange>
                     <ADD LineNo="41" ColNo="50">
                        <NodeTimepointValue>
                           <NodeId>Sub</NodeId>
                           <NodeStateValue>FINISHED</NodeStateValue>
                           <Timepoint>START</Timepoint>
                        </NodeTimepointValue>
                        <RealValue>1.0</RealValue>
                     </ADD>
                  </GE>
               </EndCondition>
               <NodeBody>
                  <Assignment>
                     <IntegerVariable>x</IntegerVariable>
                     <NumericRHS>
                        <IntegerValue>5</IntegerValue>
                     </NumericRHS>
                  </Assignment>
               </NodeBody>
            </Node>
         </NodeList>
      </NodeBody>
   </Node>
</PlexilPlan>